#!/usr/bin/env python3
"""Batch-author base.json + concourse.png for the 55 Privateer bases that
don't have one yet. Output: assets/bases/<id>/base.json + concourse.png.

Then runs tools/gen_placeholder_concourse.py so the PNGs match the JSON.

Mapping per base:
  - display_name   : from BASES.IFF INFO name
  - dir name       : snake_case of name (matches existing convention)
  - faction label  : WCU XML faction (confed/militia/merchant/pirates/kilrathi)
                     -> "Confederation" / "Militia" / "Merchant Guild" / etc.
  - archetype      : mining/refinery/agricultural/pirate/military/pleasure,
                     driven by kind byte (see KIND_TO_ARCH)
  - hotspots       : 6 standard (Bar, CommodityExchange, ShipDealer, Equipment,
                     MissionComputer, Launch) -- matches existing achilles/helen
                     schema. The engine gates service availability separately.
"""
import os, struct, re, sys, subprocess, json
from pathlib import Path

REPO  = Path(__file__).resolve().parent.parent
BASES = REPO / "assets" / "bases"

# 1. Parse BASES.IFF for {idx -> (name, kind)}.
b = open(REPO / "gog_extracted/extracted/priv/DATA/SECTORS/BASES.IFF", "rb").read()
p = 12
bases = {}
while p < 8 + 1154:
    tag = b[p:p+4]; size = struct.unpack(">I", b[p+4:p+8])[0]
    data = b[p+8:p+8+size]
    if tag == b"INFO":
        idx = data[0]; kind = data[1]
        name = data[2:].rstrip(b"\x00").decode("latin1", "replace")
        bases[idx] = (name, kind)
    p += 8 + size + (size & 1)

# 2. Walk WCU XML for {name -> (file, faction)}.
wcu = REPO.parent / "privateer_wcu" / "sectors" / "Gemini"
file_by_name = {}
if wcu.is_dir():
    for fn in sorted(os.listdir(wcu)):
        if not fn.endswith(".system"): continue
        for line in open(wcu / fn):
            m = re.search(r'<unit name="([^"]+)" file="([^"]+)" faction="([^"]+)"', line)
            if m:
                name, file_, fac = m.group(1), m.group(2), m.group(3)
                file_by_name.setdefault(name, (file_, fac))

# 3. Directories already authored.
authored = {d for d in os.listdir(BASES) if (BASES/d/"base.json").exists()}

# 4. Helpers ---------------------------------------------------------------

def norm_id(name):
    s = name.lower().replace("'", "").replace(" ", "_").replace("-", "_")
    s = re.sub(r"[^a-z0-9_]", "", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s

# kind byte -> archetype + visual file kind label.
KIND_TO_ARCH = {
    0x01: "agricultural",   # civilian / pleasure / guild HQ / university
    0x02: "refinery",
    0x03: "mining",
    0x04: "agricultural",   # agricultural / industrial planet
    0x05: "pirate",
    0x06: "military",       # New Const, Perry, Oxford, etc.
}

def faction_label(wcu_faction: str) -> str:
    return {
        "confed":   "Confederation",
        "militia":  "Militia",
        "merchant": "Merchant Guild",
        "pirates":  "Pirates",
        "kilrathi": "Kilrathi Empire",
    }.get(wcu_faction, "")

# Hotspots for the 6 canonical services (all enabled, in matching order).
HOTSPOTS = [
    ('Bar',               'BAR',               'Drinks, rumours, and fixers'),
    ('CommodityExchange', 'COMMODITY EXCHANGE','Buy and sell cargo'),
    ('ShipDealer',        'SHIP DEALER',       'Trade up your hull'),
    ('Equipment',         'EQUIPMENT',         'Guns, shields, engines'),
    ('MissionComputer',   'MISSION COMPUTER',  'Find work'),
    ('Launch',            'LAUNCH',            'Return to flight'),
]
# Normalized rects for a 2x3 grid matching achilles/helen.
RECTS = [
    (0.04, 0.50, 0.26, 0.16),
    (0.37, 0.50, 0.26, 0.16),
    (0.70, 0.50, 0.26, 0.16),
    (0.04, 0.72, 0.26, 0.16),
    (0.37, 0.72, 0.26, 0.16),
    (0.70, 0.72, 0.26, 0.16),
]

def emit_json(dir_name: str, display: str, archetype: str, faction: str) -> str:
    """Return the textual base.json for this base."""
    faction_comment = (f'\n  "faction":       "{faction}",' if faction else "")
    # Note: leaving faction empty so the engine can default it.
    return f"""{{
  // {display} ({archetype}). Generated by tools/batch_author_bases.py.
  // Schema matches assets/bases/achilles/base.json (np-9cu.4 normalized
  // hotspot rects). Concourse art is the procedural placeholder from
  // tools/gen_placeholder_concourse.py -- real pixel art is a later task.
  "display_name":  "{display}",
  "faction":       "{faction}",

  // Economy archetype (np-9cu.2) -> drives prices in
  // assets/data/commodity_prices.json.
  "market": {{ "archetype": "{archetype}" }},

  "concourse_art": "bases/{dir_name}/concourse.png",

  "hotspots": [
{{ 'PLACEHOLDER' }}
  ]
}}"""

# Build the hotspots list as a string so the f-string above can hold it.
HOT_BLOCK = ",\n".join(
    f'    {{ "target": "{t}", "label": "{l}", "rect": [{r[0]:.2f}, {r[1]:.2f}, {r[2]:.2f}, {r[3]:.2f}], "tooltip": "{tt}" }}'
    for (t, l, tt), r in zip(HOTSPOTS, RECTS)
)
HOT_BLOCK = ",\n".join(HOT_BLOCK.split("\n"))  # squash

def emit_json_real(dir_name, display, archetype, faction):
    out = f"""{{
  // {display} ({archetype}). Generated by tools/batch_author_bases.py.
  // Schema matches assets/bases/achilles/base.json (np-9cu.4 normalized
  // hotspot rects). Concourse art is the procedural placeholder from
  // tools/gen_placeholder_concourse.py -- real pixel art is a later task.
  "display_name":  "{display}",
  "faction":       "{faction}",

  // Economy archetype (np-9cu.2) -- drives prices in
  // assets/data/commodity_prices.json.
  "market": {{ "archetype": "{archetype}" }},

  "concourse_art": "bases/{dir_name}/concourse.png",

  "hotspots": [
"""
    for i, ((t, l, tt), r) in enumerate(zip(HOTSPOTS, RECTS)):
        sep = "," if i < len(HOTSPOTS)-1 else ""
        out += (f'    {{ "target": "{t}", "label": "{l}",\n'
                f'      "rect": [{r[0]:.2f}, {r[1]:.2f}, {r[2]:.2f}, {r[3]:.2f}],\n'
                f'      "tooltip": "{tt}" }}{sep}\n')
    out += "  ]\n}\n"
    return out

# 5. Walk all 60 bases; skip the 5 already authored.
print("# Batch-authoring 55 missing base.json files + concourse.png\n")
n_written = 0
for idx in sorted(bases):
    name, kind = bases[idx]
    file_and_faction = file_by_name.get(name, ("", ""))
    wcu_file, wcu_fac = file_and_faction
    arch = KIND_TO_ARCH.get(kind, "agricultural")
    fac_label = faction_label(wcu_fac)
    dir_name = norm_id(name)

    if dir_name in authored:
        continue

    target_dir = BASES / dir_name
    target_dir.mkdir(parents=True, exist_ok=True)
    json_text = emit_json_real(dir_name, name, arch, fac_label)
    (target_dir / "base.json").write_text(json_text)
    print(f"  [+] {dir_name:24}  {name:24}  kind=0x{kind:02x}  arch={arch}  faction='{fac_label}'")
    n_written += 1

print(f"\nWrote {n_written} base.json files.")

# 6. Now invoke the placeholder concourse generator so each has a PNG.
print("\n# Generating placeholder concourse.png for each...\n")
res = subprocess.run(
    [sys.executable, "tools/gen_placeholder_concourse.py"],
    capture_output=True, text=True, cwd=REPO
)
print(res.stdout)
if res.returncode != 0:
    print(res.stderr, file=sys.stderr)
    sys.exit(res.returncode)

print("# Done.")
