#!/usr/bin/env python3
# =============================================================================
# gen_mission_templates.py — bake the recoverable briefing text into a header.
#
# Reads re/mission_text.json (the per-type summary + copy[] + ENMY/CORP pools
# extracted by re/extract_mission_text.py from the user's OWN PRIV.TRE) and
# emits src/mission_templates.gen.h: a single C++17 header exposing the same
# data as constexpr tables of std::string_view. missions.cpp #includes this
# header and uses the tables to render briefing text on demand.
#
# The briefing strings are derivative game text — they stay local to the
# build (this script + the generated header are NOT tracked; the .json in
# re/ is gitignored). The only thing committed alongside the code is the
# short token-substitution rule ("$EN -> outlaw faction display name" etc),
# which is pure data plumbing, no copying.
#
# Usage:
#   tools/gen_mission_templates.py [path/to/mission_text.json] \
#       [path/to/output.h]
#   (defaults: re/mission_text.json -> src/mission_templates.gen.h)
# =============================================================================
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO   = Path(__file__).resolve().parents[1]
DEFAULT_IN  = REPO / "re" / "mission_text.json"
DEFAULT_OUT = REPO / "src" / "mission_templates.gen.h"


def c_string(s: str) -> str:
    """Encode a Python str as a C++ raw-string-literal fragment.

    Raw strings can't contain ")gen" inside (since that's our delimiter) and
    must avoid a backslash before the closing quote, so we fall back to a
    regular string with explicit escaping if either boundary case hits.
    """
    if "R\"gen(" not in s and ")" not in s.split("gen", 1)[-1]:
        return f'R"gen({s})gen"'
    # fallback: escape backslashes + quotes for a plain "..." literal
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_array(name: str, entries: list[str], indent: str = "    ") -> None:
    """Write a `constexpr std::string_view k_name[] = { ... };` block."""
    print(f"{indent}// {len(entries)} entries.")
    print(f"{indent}inline constexpr std::string_view {name}[] = {{")
    for i, e in enumerate(entries):
        comma = "," if i + 1 < len(entries) else ""
        print(f"{indent}    {c_string(e)}{comma}")
    print(f"{indent}}};")
    print()


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_IN
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT

    if not src.exists():
        sys.stderr.write(f"[gen_mission_templates] missing input: {src}\n")
        return 1

    data = json.loads(src.read_text())
    types = data.get("types", {})
    required = ("PTRL", "SCOU", "DFND", "CRGO", "ATAK", "BNTY", "ENMY", "CORP")
    if not all(key in types for key in required):
        # mission_text.json is an optional local extraction from the user's own
        # game data. A checkout ships a valid fallback header; never replace it
        # with an empty-but-successful header when the private catalog is absent.
        existing = dst.read_text(encoding="utf-8") if dst.is_file() else ""
        markers = ("k_corp", "k_enmy", "k_ptrl_summary", "k_scou_summary",
                   "k_dfnd_summary", "k_crgo_summary", "k_atak_summary",
                   "k_bnty_summary")
        if all(marker in existing for marker in markers):
            print(f"[gen_mission_templates] optional catalog incomplete; preserving fallback {dst}")
            return 0
        missing = ", ".join(key for key in required if key not in types)
        sys.stderr.write(
            f"[gen_mission_templates] incomplete input ({missing}) and no valid fallback: {dst}\n")
        return 1

    # Build the output in one shot so the .h is atomic on disk.
    lines: list[str] = []
    out_write = lines.append
    out_write("// AUTOGENERATED by tools/gen_mission_templates.py — do NOT hand-edit.")
    out_write("// Regenerate by running the script (CMake custom_command).")
    out_write("#pragma once")
    out_write("#include <cstddef>")
    out_write("#include <string_view>")
    out_write("")
    out_write("namespace missions::templates {")
    out_write("")
    out_write("// Source pools.")
    if "ENMY" in types:
        emit_array_to(lines, "k_enmy", types["ENMY"].get("names", []))
    if "CORP" in types:
        emit_array_to(lines, "k_corp", types["CORP"].get("names", []))
    out_write("")
    out_write("// Per-type tables (PTRL/SCOU/DFND/CRGO/ATAK/BNTY). One-line summary")
    out_write("// + N copy variants per type. Token substitution is left to the")
    out_write("// caller: src/missions.cpp's render_briefing() walks the chosen")
    out_write("// copy template and substitutes every supported $XX token.")
    for key in ("PTRL", "SCOU", "DFND", "CRGO", "ATAK", "BNTY"):
        if key not in types:
            continue
        rec = types[key]
        summary = rec.get("summary", "")
        copies  = rec.get("copy", [])
        lkey    = key.lower()
        out_write(f"// ---- {key} ----")
        out_write(f"inline constexpr std::string_view k_{lkey}_summary = {c_string(summary)};")
        out_write(f"inline constexpr std::size_t    k_{lkey}_count   = {len(copies)};")
        emit_array_to(lines, f"k_{lkey}_copy", copies)
    out_write("")
    out_write("} // namespace missions::templates")
    out_write("")

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(lines))
    n_types = sum(1 for k in ("PTRL", "SCOU", "DFND", "CRGO", "ATAK", "BNTY") if k in types)
    n_enmy  = len(types.get("ENMY", {}).get("names", []))
    n_corp  = len(types.get("CORP", {}).get("names", []))
    n_copy  = sum(len(types.get(k, {}).get("copy", []))
                  for k in ("PTRL", "SCOU", "DFND", "CRGO", "ATAK", "BNTY"))
    print(f"[gen_mission_templates] {src} -> {dst}")
    print(f"[gen_mission_templates]   types={n_types}  enmy={n_enmy}  corp={n_corp}  copy_total={n_copy}")
    return 0


def emit_array_to(buf: list[str], name: str, entries: list[str], indent: str = "    ") -> None:
    """Append a constexpr string_view array block to `buf`."""
    buf.append(f"{indent}// {len(entries)} entries.")
    buf.append(f"{indent}inline constexpr std::string_view {name}[] = {{")
    for i, e in enumerate(entries):
        comma = "," if i + 1 < len(entries) else ""
        buf.append(f"{indent}    {c_string(e)}{comma}")
    buf.append(f"{indent}}};")
    buf.append("")


if __name__ == "__main__":
    sys.exit(main())
