#!/usr/bin/env python3
"""regenerate_sprite_showroom.py — emit assets/systems/sprite_showroom.json,
a grid of every 3D-derived ship SPRITE atlas (not the meshes).

Counterpart to regenerate_mesh_showroom.py. Where that scene drops the
raw .obj meshes into the world, this one drops billboard sprites driven
by the `atlas_manifest_3d.json` files we batch-rendered from those meshes.
Flying around it shows the view-sphere atlas doing its thing — each ship
swaps to the nearest-angle sprite cell as the camera orbits.

Why a separate scene:
    * Confirms the 3D→sprite pipeline end to end: mesh → 80-cell capture
      → atlas manifest → in-engine billboard. If a ship looks wrong here
      but right in the mesh showroom, the bug is in the atlas, not the mesh.
    * Sprites are dramatically cheaper to draw than meshes, so this is
      also the scene that proves the ships are gameplay-ready (you'd fly
      past dozens of these in a real system, not full 57k-tri meshes).

No per-ship orientation needed: the atlas cells already encode every
view angle, and the engine's sprite picker chooses the right one from
the camera's relative azimuth/elevation. We just place + size them.

Usage:
    tools/regenerate_sprite_showroom.py
    tools/regenerate_sprite_showroom.py --cols 6 --spacing 400 --length 120
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

REPO     = Path(__file__).resolve().parents[1]
SHIPS    = REPO / "assets" / "ships"
OUT_PATH = REPO / "assets" / "systems" / "sprite_showroom.json"

# Reuse the canonical ship roster (display names) from the mesh showroom
# generator so the two scenes always cover the same set of ships.
sys.path.insert(0, str(Path(__file__).parent))
from regenerate_mesh_showroom import KEEP_AND_RENAME   # noqa: E402


def discover_sprite_ships() -> list[str]:
    """Display names that actually have an atlas_manifest_3d.json on disk."""
    names = sorted(set(KEEP_AND_RENAME.values()))
    out = []
    for name in names:
        manifest = SHIPS / name / "atlas_manifest_3d.json"
        if manifest.exists():
            out.append(name)
        else:
            print(f"note: no atlas_manifest_3d.json for {name!r}; skipping",
                  file=sys.stderr)
    return out


def build_layout(names: list[str], cols: int, spacing: float
                 ) -> list[tuple[str, float, float]]:
    rows = math.ceil(len(names) / cols)
    placed = []
    for idx, name in enumerate(names):
        r = idx // cols
        c = idx %  cols
        x = (c - (cols - 1) / 2.0) * spacing
        z = ((rows - 1) / 2.0 - r) * spacing
        placed.append((name, x, z))
    return placed


def build_showroom(names: list[str], cols: int, spacing: float,
                   length: float) -> dict:
    placed = build_layout(names, cols, spacing)
    rows    = math.ceil(len(names) / cols)
    grid_d  = (rows - 1) * spacing
    spawn_y = grid_d * 0.4 + 200
    spawn_z = grid_d * 0.6 + 800
    look_z  = -grid_d * 0.15

    ship_sprites = [{
        "atlas":          f"ships/{name}/atlas_manifest_3d",
        "position":       [round(x, 2), 0, round(z, 2)],
        "length_meters":  length,
        "lights_enabled": True,    # show authored .lights.json sidecars in-scene
        "inert":          True,    # static showroom — no AI / physics
    } for name, x, z in placed]

    navs = [{"name": "Showroom Center", "kind": "nav",
             "position": [0, round(spawn_y * 0.7, 2), 0]}]
    navs += [{"name": name, "kind": "nav", "position": [round(x, 2), 0, round(z, 2)]}
             for name, x, z in placed]

    return {
        "name":        "Sprite Showroom (3D-derived atlases)",
        "description": (
            f"Auto-generated by tools/regenerate_sprite_showroom.py. "
            f"{len(names)} ship sprite atlases (atlas_manifest_3d) laid out "
            f"{cols}x{rows} at {spacing}m. Each is a view-sphere billboard — "
            f"fly around and watch the atlas pick the nearest-angle cell."),
        "skybox_seed":         "troy",
        "star":                {"preset": "yellow"},
        "studio_lighting":     True,
        "asteroid_fields":     [],
        "placed_meshes":       [],
        "placed_sprites":      [],
        "placed_ship_sprites": ship_sprites,
        "nav_points":          navs,
        "player_start": {
            "position": [0, round(spawn_y, 2), round(spawn_z, 2)],
            "look_at":  [0, 0, round(look_z, 2)],
        },
    }


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--cols",    type=int,   default=6)
    p.add_argument("--spacing", type=float, default=400.0)
    p.add_argument("--length",  type=float, default=120.0,
                   help="billboard length_meters for every ship (default: 120)")
    args = p.parse_args()

    names = discover_sprite_ships()
    if not names:
        print("no atlas_manifest_3d.json files found — run "
              "tools/render_3d_sprite_atlases.py first", file=sys.stderr)
        return 1

    scene = build_showroom(names, args.cols, args.spacing, args.length)
    OUT_PATH.write_text(json.dumps(scene, indent=2, ensure_ascii=False) + "\n")

    rows = math.ceil(len(names) / args.cols)
    print(f"wrote {OUT_PATH.relative_to(REPO)}")
    print(f"  {len(names)} sprite atlases  {args.cols}x{rows}  "
          f"spacing={args.spacing}m  length={args.length}m")
    return 0


if __name__ == "__main__":
    sys.exit(main())
