// -----------------------------------------------------------------------------
// missions.cpp — Mission Computer: generation, accept/complete, screen body.
//
// See missions.h for the design (data-driven generation, the headless split,
// board persistence policy, and the np-ma2.1 kill-path wiring). This file is
// two halves, mirroring economy.cpp:
//
//   1. The MODEL — generate() / accept() / complete_delivery() / abandon() /
//      on_target_destroyed(). Pure logic: it reads the commodity catalog, the
//      galaxy graph + neighbouring system JSON (for real destination bases),
//      moves credits/cargo ONLY through player:: helpers, and pushes comm
//      lines. No ImGui, no audio — links into tools/test_missions.cpp.
//
//   2. The VIEW — the Mission Computer ImGui screen body, registered with
//      base_screens via the np-9cu.4 hook seam. Compiled out under
//      MISSIONS_HEADLESS so the offline harness needn't drag in the UI stack.
//
// ---- TUNING CONSTANTS (reward model #11; generation knobs #10) --------------
// All knobs in one place so the unit tests in tools/test_missions.cpp can pin
// the model down with concrete bands. The pay block below is the literal
// transcription of re/mission_economy.md's "Tuning block" section; the
// generation-only knobs (`k_cargo_units_*`, `k_bounty_count_*`, `k_max_*`)
// are kept here only because #10's generators still reference them — they
// are NOT part of the reward model and won't be sampled by compute_reward().
// -----------------------------------------------------------------------------

#include "missions.h"

#include "comm.h"
#include "commodity.h"
#include "faction.h"
#include "galaxy.h"
#include "player.h"
#include "system_def.h"

// Generated template tables — one constexpr blob per type + ENMY/CORP pools.
// Autogenerated by tools/gen_mission_templates.py (wired into CMake) from
// re/mission_text.json. Keeping this a build artefact means we never hand-
// paste briefing prose into source: the catalogue is the single source.
#include "mission_templates.gen.h"

#ifndef MISSIONS_HEADLESS
#include "base_screens.h"
#include "ship_class.h"
#include "sfx.h"
#include "imgui.h"
#include "sokol_app.h"
#endif

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <ctime>
#include <algorithm>
#include <cstring>
#include <optional>
#include <queue>
#include <random>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>
#include <vector>

// Pull in the JSON reader for the giver-faction lookup on the origin base.
#include "json.h"

namespace missions {

// One reachable destination base, with its galaxy distance in jumps. Lives
// at the top of missions:: (not in anonymous) so the test can link against
// `std::vector<DestBase>` and match the function signature on both sides.
struct DestBase {
    std::string system_id;
    std::string system_name;
    std::string base_id;
    std::string base_name;   // the nav-point display name ("Helen Planet")
    int         jumps = 0;
};

namespace {

// ---- tuning knobs -----------------------------------------------------------
//
// ---- per-hop + per-source multiplier (the reward model's "shape") -------------
// Per-hop addition: the "further out the mission, the more it pays" rule.
// Source multipliers: position the result WITHIN the k_pay band (they do NOT
// define the band — k_pay[type].base does).
constexpr int64_t k_pay_per_hop       = 2750;    // credits per shortest jump
constexpr int64_t k_pay_floor         = 1000;    // defensive lower bound, credits
constexpr double  k_src_mult_computer = 0.85;    // Mission Computer
constexpr double  k_src_mult_merc     = 1.10;    // Mercenaries' Guild (top of band)
constexpr double  k_src_mult_merchant = 1.00;    // Merchants' Guild (mid)

// ---- per-type base pay + symmetric jitter (the reward model's "amount") -----
struct PayKnobs { int64_t base; int64_t spread; };
// Indexed by MissionType (0..5): Patrol, Scout, Attack, DefendBase, Bounty, Cargo.
constexpr PayKnobs k_pay[6] = {
    /* Patrol     */ { 10000,  850 },   // band 9150–10850 (the headline number)
    /* Scout      */ {  5500,  500 },   // ~0.55× Patrol
    /* Attack     */ {  8000,  700 },   // ~0.80× Patrol
    /* DefendBase */ {  8000,  700 },   // same as Attack ("≈ Attack")
    /* Bounty     */ { 11000,  900 },   // ~1.10× Patrol ("a bit more")
    /* Cargo      */ {     0,    0 },   // uses the cargo formula below; base is 0
};

// ---- cargo-specific bits (NOT multiplied by src; per-hop + value are dominant)
constexpr int64_t k_cargo_base_fee     = 250;    // flat handling fee, credits
constexpr double  k_cargo_value_margin = 0.60;   // share of cargo_value paid
constexpr int64_t k_cargo_value_cap    = 6000;   // cap on the value-share term so
                                                 // a high-value haul can't dwarf a
                                                 // far patrol; keeps per-hop dominant

// ---- generation-only knobs (NOT part of the reward model; #10 owns these) ---
// Cargo unit count range (plausible vs a ~100-unit Tarsus hold) + bounty kill
// count range. (#10 2b consumed the legacy per-board-count + pay-math knobs;
// generate() now mixes types per slot and prices every offer via #11.)
constexpr int k_cargo_units_min    = 8;
constexpr int k_cargo_units_max    = 28;

// ---- #10 per-type tuning (NOT the reward model; the generators read these) --
// Attack / DefendBase kill-count range. Bounded so the briefing templates'
// $DO ranges stay plausible. Patrol sweeps every non-base nav in the system
// (no count knob here) so its $NN scales naturally with system size.
// Bounty is a single named target (count_required always 1) — no range knob.
// Issue #24: board offer count is FIXED per source — the Mission Computer
// shows 5, each Guild board shows 4. The min/max pair was a 5–8 random
// swing; that violated the rule and let a player be deluged with 8 offers
// at a heavy base.
constexpr int k_board_size_computer = 5;   // Mission Computer offer count
constexpr int k_board_size_guild    = 4;   // Merc / Merchants guild offer count
constexpr int k_max_attack_hostiles= 5;
constexpr int k_min_attack_hostiles= 2;
constexpr int k_max_defend_hostiles= 6;
constexpr int k_min_defend_hostiles= 2;

// Board refresh window: the visible board is reseeded once per this many wall-
// clock seconds (plus the base id), so it feels alive between visits but is
// stable within a sitting and never per-frame noise. 30 min.
constexpr int64_t k_board_refresh_secs  = 1800;

// Coarse per-unit "mission value" heuristic (credits/unit) — see header. NOT
// the market price; just enough that luxury/weapons jobs pay more than ore.
int nominal_unit_value(const std::string& category) {
    if (category == "MAGIC")   return 100;
    if (category == "WEAPONS") return 80;
    if (category == "LUXURY")  return 60;
    if (category == "MEDICAL") return 55;
    if (category == "FOOD")    return 25;
    if (category == "RAWMAT")  return 20;
    return 35;   // sensible default for the other categories
}

// FNV-1a over a string — small, stable, no deps. Seeds the per-base board.
uint64_t fnv1a(const std::string& s) {
    uint64_t h = 1469598103934665603ull;
    for (unsigned char c : s) { h ^= c; h *= 1099511628211ull; }
    return h;
}

// Read the origin base's display faction from its base.json (flavour for the
// mission giver). "Independent" when absent — never fatal.
std::string giver_faction_of(const std::string& base_id) {
    const json::Value root =
        json::parse_file("assets/bases/" + base_id + "/base.json");
    if (root.is_object() && root.contains("faction")) {
        const std::string f = root["faction"].string_or("");
        if (!f.empty()) return f;
    }
    return "Independent";
}

// Append every dockable base in `system_id` (loaded fresh from its JSON) to
// `out`, tagging each with `jumps`. Skips the origin base itself.
void add_bases_from_system(const galaxy::Galaxy& g, const std::string& system_id,
                           const std::string& origin_base, int jumps,
                           std::vector<missions::DestBase>& out) {
    const std::string path = g.json_path_for(system_id);
    if (path.empty()) return;
    std::optional<StarSystem> sys = load_system(path);
    if (!sys) return;

    std::string sys_name = sys->name;
    if (const galaxy::SystemEntry* e = g.find(system_id); e && !e->display_name.empty())
        sys_name = e->display_name;

    for (const NavPointDef& nav : sys->nav_points) {
        if (!nav.dockable || nav.base_id.empty()) continue;
        if (jumps == 0 && nav.base_id == origin_base) continue;  // not to self
        out.push_back(missions::DestBase{ system_id, sys_name, nav.base_id, nav.name, jumps });
    }
}

// Every dockable base reachable from the origin, tagged with its shortest
// jump distance. Breadth-first traversal matters here: rewards scale per hop,
// so a longer non-shortest route would silently overpay the contract.
std::vector<missions::DestBase> collect_dest_bases(const galaxy::Galaxy& g,
                                         const std::string& system_id,
                                         const std::string& origin_base) {
    std::vector<missions::DestBase> out;
    std::queue<std::string> pending;
    std::unordered_map<std::string, int> distance;
    pending.push(system_id);
    distance.emplace(system_id, 0);

    while (!pending.empty()) {
        const std::string current = pending.front();
        pending.pop();
        const int jumps = distance.at(current);
        add_bases_from_system(g, current, origin_base, jumps, out);

        for (const std::string& neighbor : g.neighbors(current)) {
            if (distance.contains(neighbor)) continue;
            distance.emplace(neighbor, jumps + 1);
            pending.push(neighbor);
        }
    }
    return out;
}

// Plot-only/special factions are not ordinary contract fodder. In particular,
// the unique Steltek drone belongs to the campaign and must never appear as a
// randomly generated "rogue Steltek" bounty, attack wave, or base assault.
bool is_procedural_combat_target(Faction f) {
    return f != Faction::Steltek;
}

// Outlaw factions = those the lawful universe already distrusts (negative
// baseline-to-player). Derived from reputation data, then constrained to the
// conventional factions procedural mission boards are allowed to target.
std::vector<Faction> outlaw_factions() {
    std::vector<Faction> out;
    for (int i = 0; i < kFactionCount; ++i) {
        const Faction faction = (Faction)i;
        if (g_faction_baseline_to_player[i] < 0 &&
            is_procedural_combat_target(faction)) {
            out.push_back(faction);
        }
    }
    return out;
}

// Issue #107: factions the OFFERING base's faction views as Hostile in the
// stance matrix. Used for Attack / DefendBase / Bounty target selection so
// the contract is faction-appropriate: a pirate base offers "kill Confed",
// a Confed base offers "kill pirate", etc. — never "kill your own kind".
// Falls back to the outlaw pool for Independent / unknown bases so the
// target list is never empty.
std::vector<Faction> hostile_targets_for(Faction giver) {
    const int gi = (int)giver;
    if (gi < 0 || gi >= kFactionCount) return outlaw_factions();
    std::vector<Faction> out;
    for (int i = 0; i < kFactionCount; ++i) {
        const Faction target = (Faction)i;
        if (i == gi) continue;                       // never target self
        if (!is_procedural_combat_target(target)) continue;
        if (g_faction_stance[gi][i] == Stance::Hostile)
            out.push_back(target);
    }
    return out;
}

// Convert a generated offer to its persistent accepted form (player.h).
ActiveMission to_active(const Mission& m) {
    ActiveMission a;
    a.id             = m.id;
    a.type           = (int)m.type;
    a.source         = (int)m.source;        // #7: MissionSource -> save-stable int
    a.giver_faction  = m.giver_faction;
    a.title          = m.title;
    a.reward         = m.reward;
    a.commodity_id   = m.commodity_id;
    a.units          = m.units;
    a.dest_system    = m.dest_system;
    a.dest_base      = m.dest_base;
    a.target_faction = m.target_faction;
    a.count_required = m.count_required;
    a.progress       = 0;
    // ---- #7 per-type payload ----
    a.target_system         = m.target_system;
    a.nav_targets           = m.nav_targets;
    a.nav_count             = m.nav_count;
    a.hostiles_required     = m.hostiles_required;
    a.target_base           = m.target_base;
    a.bounty_region         = m.bounty_region;
    a.last_seen_system      = m.last_seen_system;
    a.last_seen_alt_system  = m.last_seen_alt_system;
    // #12: per-mission progress state starts blank on accept — a reach flag
    // per nav target (all unreached), shared kill counter at zero (set above).
    a.nav_done.assign(m.nav_targets.size(), (uint8_t)0);
    return a;
}

// ---- the cached boards (transient module state; NOT saved) ------------------
// One board per MissionSource (Computer / MercenariesGuild / MerchantsGuild),
// indexed by the enum's int value. Regenerated together on each dock so the
// three computer screens at a base each show their own stable mix.
std::vector<Mission> g_boards[3];
std::string          g_boards_base;   // base the cached boards belong to
} // namespace        // anon ends BEFORE the #9 + #11 helpers so the test
                     // driver can link against them as `missions::X`.

// =========================================================================
// #9 nav/distance helpers — pure, declared in missions:: so the unit tests
// can call them without an anonymous-namespace workaround. NOT exposed in
// missions.h (they're a #9-layer concern only, not a stable part of the
// mission system API yet).
// =========================================================================

// A single non-base nav point (kind != "jump" and base_id empty), as a name
// + world position. Used by Patrol/Scout/Attack generators to pick a target.
struct NavRef {
    std::string name;
    HMM_Vec3    pos;
};

// Every nav point in `system_id` that isn't a dockable base (jump points and
// regular nav points are both included). Patrol / Scout / Attack all reuse
// this: jump navs are valid "go visit" targets for a system-wide sweep, and
// bases are skipped because the player already interacts with them via the
// docking/comm flow, not a nav-target reach.
std::vector<NavRef> nonbase_navs(const galaxy::Galaxy& g,
                                  const std::string& system_id) {
    std::vector<NavRef> out;
    const std::string path = g.json_path_for(system_id);
    if (path.empty()) return out;
    std::optional<StarSystem> sys = load_system(path);
    if (!sys) return out;
    for (const NavPointDef& n : sys->nav_points) {
        if (!n.base_id.empty())          continue;   // it's a base — skip
        out.push_back({ n.name, n.position });
    }
    return out;
}

// Every dockable base in `system_id` except `except_base`. Reuses
// `add_bases_from_system` so the cross-system cargo case (which already
// needs a system name + jump distance) keeps a single loader path.
std::vector<DestBase> bases_in_system(const galaxy::Galaxy& g,
                                       const std::string& system_id,
                                       const std::string& except_base) {
    std::vector<DestBase> out;
    add_bases_from_system(g, system_id, except_base, /*jumps=*/0, out);
    return out;
}

// Shortest hop count from `from_sys` to `to_sys` over `g`. -1 = unreachable,
// 0 = same system. Implemented via a Dijkstra-style min-heap so a future
// weighted graph is a drop-in (today every edge is unit weight — the queue
// just degenerates into BFS). Capped at k_max_hops to bound work on an
// adversarial universe; 16 is well above the current 11-hop diameter of the
// real assets/galaxy.json with slack to spare.
//
// Public in missions.h so the navmap mission-status panel can pick a jump
// nav on the shortest path toward a cross-system cargo/bounty target.
constexpr int k_max_hops = 16;
int hops_between(const galaxy::Galaxy& g,
                 const std::string& from_sys,
                 const std::string& to_sys) {
    if (from_sys == to_sys) return 0;
    using Pair = std::pair<int, std::string>;   // (distance, system_id)
    auto cmp = [](const Pair& a, const Pair& b) { return a.first > b.first; };
    std::priority_queue<Pair, std::vector<Pair>, decltype(cmp)> pq(cmp);
    std::unordered_map<std::string, int> dist;
    pq.push({0, from_sys});
    dist[from_sys] = 0;
    while (!pq.empty()) {
        const Pair top = pq.top(); pq.pop();
        const int    d = top.first;
        const std::string& s = top.second;
        if (s == to_sys) return d;
        if (d >= k_max_hops)              continue;   // cap (don't expand past)
        if (d > dist[s])                   continue;   // stale entry
        for (const std::string& nb : g.neighbors(s)) {
            const int nd = d + 1;
            auto it = dist.find(nb);
            if (it == dist.end() || nd < it->second) {
                dist[nb] = nd;
                pq.push({nd, nb});
            }
        }
    }
    return -1;
}

// Bounty search region: the current system ("last seen") + up to 2 of its
// neighbours, chosen deterministically from `rng`. The vector size is 1..3;
// the first entry is always `system_id` itself.
std::vector<std::string> bounty_region(const galaxy::Galaxy& g,
                                       const std::string& system_id,
                                       std::mt19937_64& rng) {
    std::vector<std::string> out;
    out.push_back(system_id);                           // "last seen" is current
    std::vector<std::string> nbrs = g.neighbors(system_id);
    std::shuffle(nbrs.begin(), nbrs.end(), rng);        // deterministic for seed
    for (const std::string& nb : nbrs) {
        if (out.size() >= 3) break;
        out.push_back(nb);
    }
    return out;
}

// =========================================================================
// #11 reward model — pure, declared in missions:: so test_missions.cpp can
// sweep RNG seeds and assert bands against the spec without touching UI.
// =========================================================================

// MissionSource -> src multiplier. Single source of truth so the formula
// only knows about per-type bases, not per-source strings.
double src_mult_of(MissionSource s) {
    switch (s) {
        case MissionSource::Computer:         return k_src_mult_computer;
        case MissionSource::MercenariesGuild: return k_src_mult_merc;
        case MissionSource::MerchantsGuild:   return k_src_mult_merchant;
    }
    return k_src_mult_merchant;   // safe default for an unknown enum
}

// Pure reward function. `hops` is clamped to >= 0; `cargo_value` is only
// consulted for MissionType::CargoDelivery (use 0 for everything else).
// `rng` is consumed exactly once for non-cargo types (the jitter draw).
int64_t compute_reward(MissionType type, MissionSource src, int hops,
                       int64_t cargo_value, std::mt19937_64& rng) {
    hops = (hops < 0) ? 0 : hops;                      // clamp hops >= 0

    if (type == MissionType::CargoDelivery) {
        // Cargo: handling (flat) + capped value share + per_hop, then floored.
        const int64_t handling = k_cargo_base_fee;
        int64_t value_share = (int64_t)std::llround((double)cargo_value *
                                                     k_cargo_value_margin);
        if (value_share > k_cargo_value_cap) value_share = k_cargo_value_cap;
        if (value_share < 0)                 value_share = 0;  // belt + braces
        const int64_t per_hop = k_pay_per_hop * hops;
        const int64_t total   = handling + value_share + per_hop;
        return total < k_pay_floor ? k_pay_floor : total;
    }

    // Non-cargo: jitter → ×src_mult → +per_hop → max(floor).
    const int      idx    = (int)type;                  // k_pay is 0..5
    const int64_t  base   = k_pay[idx].base;
    const int64_t  spread = k_pay[idx].spread;
    std::uniform_int_distribution<int64_t> jit(-spread, spread);
    const int64_t  jittered = base + jit(rng);
    const double   mult     = src_mult_of(src);
    // jittered is at most 11900 (=Bounty max base); *1.10 fits easily in int64
    // even at the widest jitter window, so the double multiply is safe.
    int64_t base_pay = (int64_t)std::llround((double)jittered * mult);
    if (base_pay < 0) base_pay = 0;                    // clamp negative overflow
    const int64_t per_hop = k_pay_per_hop * hops;
    int64_t total   = base_pay + per_hop;
    // Mission Computer source pays a bit less than the Mercenaries' Guild
    // (0.85 vs 1.10 source mult), but the band still sat too high in playtest,
    // so we shave a random 1750–2500 cr off every Computer offer. Floor at
    // k_pay_floor so a long-hop Computer offer can't go below 1000 cr.
    if (src == MissionSource::Computer) {
        std::uniform_int_distribution<int> cut(1750, 2500);
        total -= cut(rng);
    }
    return total < k_pay_floor ? k_pay_floor : total;
}

// =========================================================================
// #10 slice 2a token substitution — pure, declared in missions:: (outside
// the anon block, same as the #9/#11 helpers) so test_missions.cpp can link
// it directly. NOT exposed in missions.h; generate() will call it shortly.
// =========================================================================

// Resolved string values for the catalog tokens. generate() fills one of
// these per offer and hands it to substitute() to render a briefing
// template. Pure data — no formatting logic, just already-resolved text.
struct TokenValues {
    std::string py;    // $PY  reward
    std::string en;    // $EN  enemy / target faction
    std::string cl;    // $CL  mission giver (client)
    std::string cg;    // $CG  commodity / cargo
    std::string dn;    // $DN  nav point
    std::string dn1;   // $DN1 nav point (first)
    std::string dn2;   // $DN2 nav point (second)
    std::string nn;    // $NN  nav count
    std::string db;    // $DB  destination / target base
    std::string ds;    // $DS  destination / target system
    std::string ds1;   // $DS1 system (first)
    std::string ds2;   // $DS2 system (second)
    std::string d_o;   // $DO  bounty region
    std::string d1;    // $D1  last-seen system
    std::string d2;    // $D2  last-seen alt system
    std::string bn;    // $BN  base name
    std::string sb;    // $SB  source base
    std::string ss;    // $SS  source system
};

// Replace every occurrence of each $TOKEN in `tmpl` with its resolved value.
// Longest token first (so $DN1 / $DN2 win over $DN, $DS1 / $DS2 over $DS),
// matched by a single left-to-right scan: at each '$' we try the known
// tokens longest-first and consume the first hit. Unknown $X sequences are
// copied through untouched (the caller asserts none survive). Pure — no
// global state, allocates only the result string.
std::string substitute(std::string_view tmpl, const TokenValues& v) {
    // (token, value) pairs, declared longest-first so the scan below is a
    // straight prefix test with no extra sorting at call time.
    const std::pair<std::string_view, const std::string*> table[] = {
        { "$DN1", &v.dn1 }, { "$DN2", &v.dn2 },
        { "$DS1", &v.ds1 }, { "$DS2", &v.ds2 },
        { "$PY", &v.py }, { "$EN", &v.en }, { "$CL", &v.cl }, { "$CG", &v.cg },
        { "$DN", &v.dn }, { "$NN", &v.nn }, { "$DB", &v.db }, { "$DS", &v.ds },
        { "$DO", &v.d_o }, { "$D1", &v.d1 }, { "$D2", &v.d2 },
        { "$BN", &v.bn }, { "$SB", &v.sb }, { "$SS", &v.ss },
    };

    std::string out;
    out.reserve(tmpl.size());
    for (size_t i = 0; i < tmpl.size();) {
        if (tmpl[i] == '$') {
            const std::string_view rest = tmpl.substr(i);
            bool matched = false;
            for (const auto& [tok, val] : table) {
                if (rest.substr(0, tok.size()) == tok) {
                    out += *val;
                    i += tok.size();
                    matched = true;
                    break;
                }
            }
            if (matched) continue;
        }
        out += tmpl[i++];   // ordinary char, or an unknown $X — copy through
    }
    return out;
}

// =========================================================================
// #10 slice 2b — per-type generation helpers. Anonymous (internal linkage);
// the public entry point stays generate() below. These translate #9's nav /
// base / region data + the generated briefing catalogue into a finished
// Mission, source-aware, with #11 rewards and 2a token substitution.
// =========================================================================
namespace {

// Count of the generated CORP pool (for the random-client roll).
constexpr std::size_t k_corp_count =
    sizeof(missions::templates::k_corp) / sizeof(missions::templates::k_corp[0]);

// Stable lowercase tag woven into a mission id ("achilles-ptrl3").
const char* type_short(MissionType t) {
    switch (t) {
        case MissionType::Patrol:        return "ptrl";
        case MissionType::Scout:         return "scou";
        case MissionType::Attack:        return "atak";
        case MissionType::DefendBase:    return "dfnd";
        case MissionType::Bounty:        return "bnty";
        case MissionType::CargoDelivery: return "crgo";
    }
    return "msn";
}

// Briefing templates (one summary + N long-form copy) for a type.
struct TemplatePack {
    std::string_view        summary;
    const std::string_view* copy;
    std::size_t             count;
};
TemplatePack templates_for(MissionType t) {
    using namespace missions::templates;
    switch (t) {
        case MissionType::Patrol:        return { k_ptrl_summary, k_ptrl_copy, k_ptrl_count };
        case MissionType::Scout:         return { k_scou_summary, k_scou_copy, k_scou_count };
        case MissionType::Attack:        return { k_atak_summary, k_atak_copy, k_atak_count };
        case MissionType::DefendBase:    return { k_dfnd_summary, k_dfnd_copy, k_dfnd_count };
        case MissionType::Bounty:        return { k_bnty_summary, k_bnty_copy, k_bnty_count };
        case MissionType::CargoDelivery: return { k_crgo_summary, k_crgo_copy, k_crgo_count };
    }
    return { k_ptrl_summary, k_ptrl_copy, k_ptrl_count };
}

// The eligible mission types for a board source (issue #10 / #0 mix).
std::vector<MissionType> allowed_types(MissionSource s) {
    switch (s) {
        case MissionSource::MercenariesGuild:
            return { MissionType::Patrol, MissionType::Scout, MissionType::Attack,
                     MissionType::DefendBase, MissionType::Bounty };
        case MissionSource::MerchantsGuild:
            return { MissionType::CargoDelivery, MissionType::Bounty };
        case MissionSource::Computer:
        default:
            return { MissionType::Patrol, MissionType::Scout, MissionType::Attack,
                     MissionType::DefendBase, MissionType::Bounty,
                     MissionType::CargoDelivery };
    }
}

// Display name of a system id (galaxy catalog), falling back to the id.
std::string system_display_name(const galaxy::Galaxy& g, const std::string& sys_id) {
    if (const galaxy::SystemEntry* e = g.find(sys_id); e && !e->display_name.empty())
        return e->display_name;
    return sys_id;
}

// Display (nav) name of a base within a system, falling back to the id.
std::string base_display_name(const galaxy::Galaxy& g, const std::string& sys_id,
                              const std::string& base_id) {
    const std::string path = g.json_path_for(sys_id);
    if (!path.empty()) {
        if (std::optional<StarSystem> sys = load_system(path)) {
            for (const NavPointDef& nav : sys->nav_points)
                if (nav.base_id == base_id && !nav.name.empty()) return nav.name;
        }
    }
    return base_id;
}

// Human list of system display names: "Troy, Pyrenees and War".
std::string join_system_names(const galaxy::Galaxy& g,
                              const std::vector<std::string>& ids) {
    std::string out;
    for (size_t i = 0; i < ids.size(); ++i) {
        const std::string nm = system_display_name(g, ids[i]);
        if (i == 0)                    out  = nm;
        else if (i + 1 == ids.size())  out += " and " + nm;
        else                           out += ", " + nm;
    }
    return out;
}

} // namespace

// ---- generation -------------------------------------------------------------

std::vector<Mission> generate(const std::string& base_id,
                              const std::string& system_id,
                              const galaxy::Galaxy& g,
                              uint64_t seed,
                              MissionSource source) {
    std::vector<Mission> out;
    std::mt19937_64 rng(seed);

    // Shared, read-once context (pure: galaxy graph + catalogs, no globals).
    const std::string             giver    = giver_faction_of(base_id);
    const std::string             sys_name = system_display_name(g, system_id);
    const std::vector<NavRef>     navs     = nonbase_navs(g, system_id);
    const std::vector<DestBase>   dests    = collect_dest_bases(g, system_id, base_id);
    const std::vector<Commodity>& cat      = commodity::all();
    const std::vector<Faction>    outlaws  = outlaw_factions();
    // Issue #107: prefer targets the OFFERING faction is Hostile toward
    // (pirate base -> Confed/Militia/Hunter/Kilrathi, etc.). Independent or
    // unknown bases have no alignment, so fall back to the outlaw pool.
    const Faction                 giver_f  = faction::from_name(giver);
    std::vector<Faction>          targets  = (giver_f != Faction::Count)
                                                 ? hostile_targets_for(giver_f)
                                                 : std::vector<Faction>{};
    if (targets.empty()) targets = outlaws;
    const std::vector<MissionType> types   = allowed_types(source);
    if (types.empty()) return out;

    // Small rng conveniences (single rng -> same seed yields same board).
    auto uri = [&](int lo, int hi) { return std::uniform_int_distribution<int>(lo, hi)(rng); };
    auto urz = [&](size_t n)       { return std::uniform_int_distribution<size_t>(0, n - 1)(rng); };

    // $CL: half the time the offering base's own faction, half a random corp.
    auto pick_client = [&]() -> std::string {
        if (uri(0, 1) == 0 || k_corp_count == 0) return giver;
        return std::string(missions::templates::k_corp[urz(k_corp_count)]);
    };
    // $EN / target_faction: a real outlaw faction name (so kill attribution +
    // faction::from_name resolve), falling back to "pirate" if none exist.
    auto pick_outlaw = [&]() -> std::string {
        if (targets.empty()) return "pirate";
        return faction::to_name(targets[urz(targets.size())]);
    };

    // Issue #24: board offer count is FIXED per source — Mission Computer
    // shows 5, each Guild board shows 4. No more 5-8 random swing that
    // could dump 8 offers on the player at a heavy base.
    const int slots = (source == MissionSource::Computer)
                          ? k_board_size_computer
                          : k_board_size_guild;
    for (int i = 0; i < slots; ++i) {
        const MissionType t = types[urz(types.size())];

        Mission m;
        m.id            = base_id + "-" + type_short(t) + std::to_string(i);
        m.type          = t;
        m.source        = source;
        m.giver_faction = giver;

        TokenValues v;
        v.cl = pick_client();
        const std::string enemy = pick_outlaw();
        v.en = enemy;

        int     hops        = 0;
        int64_t cargo_value = 0;

        switch (t) {
            case MissionType::Patrol: {
                if (navs.empty()) continue;                 // need somewhere to patrol
                // Patrol sweeps the WHOLE system: every non-base nav point in
                // this system is a target (bases + jump gates excluded by
                // nonbase_navs()). Shuffled only so $DN1/$DN2/$DN names in the
                // briefing aren't always the same two navs.
                std::vector<NavRef> shuf = navs;
                std::shuffle(shuf.begin(), shuf.end(), rng);
                const int n = (int)shuf.size();
                for (int k = 0; k < n; ++k) m.nav_targets.push_back(shuf[k].name);
                m.nav_count      = n;
                m.target_system  = system_id;
                m.target_faction = enemy;
                hops = 0;                                    // patrol is in-system
                v.nn  = std::to_string(n);
                v.ds  = sys_name;
                v.dn  = m.nav_targets[0];
                v.dn1 = m.nav_targets[0];
                v.dn2 = (n > 1) ? m.nav_targets[1] : m.nav_targets[0];
                v.db  = base_display_name(g, system_id, base_id);
                break;
            }
            case MissionType::Scout: {
                if (navs.empty()) continue;
                const NavRef& nav = navs[urz(navs.size())];
                m.nav_targets.push_back(nav.name);
                m.target_system  = system_id;
                m.target_faction = enemy;
                hops = 0;
                v.dn = nav.name;
                v.ds = sys_name;
                break;
            }
            case MissionType::Attack: {
                if (navs.empty()) continue;
                const NavRef& nav = navs[urz(navs.size())];
                m.nav_targets.push_back(nav.name);
                m.target_system     = system_id;
                m.target_faction    = enemy;
                m.hostiles_required = uri(k_min_attack_hostiles, k_max_attack_hostiles);
                hops = 0;
                v.dn = nav.name;
                v.ds = sys_name;
                break;
            }
            case MissionType::DefendBase: {
                if (dests.empty()) continue;                // need a base to defend
                const DestBase& d = dests[urz(dests.size())];
                m.target_system     = d.system_id;
                m.target_base       = d.base_id;
                m.target_faction    = enemy;
                m.hostiles_required = uri(k_min_defend_hostiles, k_max_defend_hostiles);
                hops = hops_between(g, system_id, d.system_id);
                if (hops < 0) hops = 0;
                v.ds = d.system_name;
                v.db = d.base_name;
                const std::vector<NavRef> dnavs = nonbase_navs(g, d.system_id);
                v.dn = dnavs.empty() ? d.base_name : dnavs[0].name;
                break;
            }
            case MissionType::Bounty: {
                if (outlaws.empty()) continue;
                m.target_faction = enemy;
                // Bounty is a SINGLE named target hunted across the region —
                // never a multi-kill contract. The briefing templates' "$EN"
                // phrasing ("find it and destroy it") is singular by design.
                m.count_required = 1;
                m.bounty_region  = bounty_region(g, system_id, rng);
                m.target_system  = system_id;
                m.last_seen_system     = m.bounty_region[0];
                m.last_seen_alt_system = (m.bounty_region.size() > 1)
                                             ? m.bounty_region[1] : m.bounty_region[0];
                // hops = nearest reachable system in the hunt region.
                int best = -1;
                for (const std::string& r : m.bounty_region) {
                    const int h = hops_between(g, system_id, r);
                    if (h >= 0 && (best < 0 || h < best)) best = h;
                }
                hops = (best < 0) ? 0 : best;
                v.d_o = join_system_names(g, m.bounty_region);
                v.ds  = v.d_o;                               // bounty copy uses $DS as the region
                v.d1  = system_display_name(g, m.last_seen_system);
                v.d2  = system_display_name(g, m.last_seen_alt_system);
                break;
            }
            case MissionType::CargoDelivery: {
                if (dests.empty() || cat.empty()) continue;
                // MerchantsGuild deliveries are almost always cross-system.
                std::vector<const DestBase*> pool;
                if (source == MissionSource::MerchantsGuild)
                    for (const DestBase& d : dests) if (d.jumps > 0) pool.push_back(&d);
                if (pool.empty())
                    for (const DestBase& d : dests) pool.push_back(&d);
                const DestBase&  d     = *pool[urz(pool.size())];
                const Commodity& c     = cat[urz(cat.size())];
                const int        units = uri(k_cargo_units_min, k_cargo_units_max);
                cargo_value = (int64_t)nominal_unit_value(c.category) * units;
                hops        = d.jumps;
                m.commodity_id     = c.id;
                m.units            = units;
                m.origin_base      = base_id;
                m.dest_system      = d.system_id;
                m.dest_base        = d.base_id;
                m.dest_base_name   = d.base_name;
                m.dest_system_name = d.system_name;
                v.cg = c.label;
                v.db = d.base_name;
                v.ds = d.system_name;
                break;
            }
        }

        const int64_t reward = compute_reward(t, source, hops, cargo_value, rng);
        m.reward = reward;
        v.py = std::to_string(reward);

        const TemplatePack tp = templates_for(t);
        m.title       = substitute(tp.summary, v);
        m.description = substitute(tp.copy[urz(tp.count)], v);
        out.push_back(std::move(m));
    }

    return out;
}

void generate_board(const std::string& base_id, const std::string& system_id,
                    const galaxy::Galaxy& g) {
    // Base seed = base id hashed, XOR a slow wall-clock window — see header.
    const int64_t window = (int64_t)std::time(nullptr) / k_board_refresh_secs;
    const uint64_t base_seed = fnv1a(base_id) ^
                               ((uint64_t)window * 0x9E3779B97F4A7C15ull);

    // Generate all three source boards off the SAME base seed but with the
    // source folded in, so the Computer / Mercenaries' / Merchants' screens
    // each show a distinct (but stable-within-a-sitting) mix at this base.
    for (int s = 0; s < 3; ++s) {
        const MissionSource src  = (MissionSource)s;
        const uint64_t       seed = base_seed ^
                                    ((uint64_t)(s + 1) * 0x9E3779B97F4A7C15ull);
        g_boards[s] = generate(base_id, system_id, g, seed, src);

        std::printf("[missions] generated %zu %s missions for '%s' (system '%s', seed %llu)\n",
                    g_boards[s].size(), source_label(src), base_id.c_str(),
                    system_id.c_str(), (unsigned long long)seed);
        for (const Mission& m : g_boards[s]) {
            std::printf("[missions]   %s | %s | %lld cr\n",
                        m.id.c_str(), m.title.c_str(), (long long)m.reward);
        }
    }
    g_boards_base = base_id;
}

const std::vector<Mission>& board(MissionSource source) {
    const int s = (int)source;
    return g_boards[(s >= 0 && s < 3) ? s : 0];
}

// ---- accept / complete ------------------------------------------------------

// True when reaching this mission's objective means leaving the player's
// CURRENT system: cargo bound for another system, a defend/attack/scout/
// patrol whose action system is a neighbour, or a bounty whose hunt region
// steps beyond the current system. Drives the "need a jump drive" refusal so
// the player can't take work they physically can't reach (FAQ rule). File-
// local: it's an accept()-time policy detail, not part of the public API.
static bool mission_is_out_of_system(const PlayerState& p, const Mission& m) {
    const std::string& here = p.current_system;
    switch (m.type) {
        case MissionType::CargoDelivery:
            return !m.dest_system.empty() && m.dest_system != here;
        case MissionType::Bounty:
            for (const std::string& r : m.bounty_region)
                if (!r.empty() && r != here) return true;
            return false;
        case MissionType::Patrol:
        case MissionType::Scout:
        case MissionType::Attack:
        case MissionType::DefendBase:
            return !m.target_system.empty() && m.target_system != here;
    }
    return false;
}

bool can_accept(const PlayerState& p, const Mission& m, int capacity) {
    // Don't accept a mission the player already has on the board —
    // the board (or at least a re-rolled snapshot) may keep showing the
    // same offer while the player can re-click Accept, which would
    // otherwise double-add it.
    for (const ActiveMission& am : p.missions) {
        if (am.id == m.id) return false;
    }
    // Issue #24: 3-active cap. The Mission Computer can hold at most 3
    // active missions; further accepts are blocked at the UI layer (the
    // board still renders all offers, but Accept is greyed). We enforce
    // it here as a hard rule so a future scripted accept can't bypass it.
    if (p.missions.size() >= 3) return false;
    // Hold-space gate for deliveries: the consignment must fit on accept.
    if (m.type == MissionType::CargoDelivery &&
        player::cargo_units_used(p) + m.units > capacity)
        return false;
    // Jump-drive gate: refuse anything that lives outside the current system
    // when the player can't jump (all six types, per the out-of-system rule).
    if (!p.has_jump_drive && mission_is_out_of_system(p, m))
        return false;
    return true;
}

bool accept(PlayerState& p, const Mission& m, int capacity) {
    if (!can_accept(p, m, capacity)) {
        // Distinguish the out-of-system refusal so the player gets a comm
        // line explaining WHY (rather than a silent no-op). Hold-space and
        // duplicate-id refusals keep the existing stdout-only diagnostic.
        if (!p.has_jump_drive && mission_is_out_of_system(p, m)) {
            std::printf("[missions] ACCEPT refused: %s is out of system, no jump drive\n",
                        m.title.c_str());
            comm::push("That job's out of system — fit a jump drive first.",
                       /*taunt=*/false);
        } else {
            std::printf("[missions] ACCEPT refused: %s (hold %d/%d, needs %d)\n",
                        m.title.c_str(), player::cargo_units_used(p), capacity, m.units);
        }
        return false;
    }
    if (m.type == MissionType::CargoDelivery) {
        // Mission cargo loads at bought_at_price 0 — it isn't yours to sell at
        // a profit, it's a consignment (v1 simplification: it still occupies
        // hold space like any cargo).
        if (!player::add_cargo(p, m.commodity_id, m.units, 0, capacity)) {
            std::printf("[missions] ACCEPT failed: could not load %d %s\n",
                        m.units, m.commodity_id.c_str());
            return false;
        }
    }
    p.missions.push_back(to_active(m));

    std::printf("[missions] ACCEPT %s | %s | reward %lld | hold %d/%d\n",
                m.id.c_str(), m.title.c_str(), (long long)m.reward,
                player::cargo_units_used(p), capacity);
    comm::push("Mission accepted: " + m.title, /*taunt=*/false);
    return true;
}

// The ONE payout path. Pay the reward of the active mission at `idx`, push
// `comm_text`, log a uniform completion line, and drop the mission from the
// active list. Every completion route (cargo, bounty, and the four objective
// types) funnels through here so the credit move + logging never drift. The
// caller owns any type-specific bookkeeping (cargo removal etc.) BEFORE this.
// Returns the reward paid.
static int64_t pay_and_drop(PlayerState& p, size_t idx,
                            const std::string& comm_text) {
    const int64_t     reward = p.missions[idx].reward;
    const std::string title  = p.missions[idx].title;
    player::add_credits(p, reward);
    std::printf("[missions] COMPLETE: %s | +%lld cr | credits %lld\n",
                title.c_str(), (long long)reward, (long long)p.credits);
    comm::push(comm_text, /*taunt=*/false);
    p.missions.erase(p.missions.begin() + (long)idx);
    return reward;
}

bool complete_delivery(PlayerState& p, const std::string& mission_id,
                       const std::string& at_base) {
    for (size_t i = 0; i < p.missions.size(); ++i) {
        ActiveMission& am = p.missions[i];
        if (am.id != mission_id || am.type != (int)MissionType::CargoDelivery)
            continue;
        if (am.dest_base != at_base) {
            std::printf("[missions] DELIVER refused: %s due at '%s', you're at '%s'\n",
                        am.title.c_str(), am.dest_base.c_str(), at_base.c_str());
            return false;
        }
        // The consignment must still be aboard (can't deliver what you sold).
        if (!player::remove_cargo(p, am.commodity_id, am.units)) {
            std::printf("[missions] DELIVER refused: consignment %d %s missing from hold\n",
                        am.units, am.commodity_id.c_str());
            return false;
        }
        pay_and_drop(p, i, "Delivery confirmed. Credits transferred.");
        return true;
    }
    std::printf("[missions] DELIVER: no active delivery '%s' for base '%s'\n",
                mission_id.c_str(), at_base.c_str());
    return false;
}

bool abandon(PlayerState& p, const std::string& mission_id) {
    for (size_t i = 0; i < p.missions.size(); ++i) {
        ActiveMission& am = p.missions[i];
        if (am.id != mission_id) continue;
        if (am.type == (int)MissionType::CargoDelivery)
            player::remove_cargo(p, am.commodity_id, am.units);   // jettison
        std::printf("[missions] ABANDON %s | %s\n", am.id.c_str(), am.title.c_str());
        comm::push("Mission abandoned: " + am.title, /*taunt=*/false);
        p.missions.erase(p.missions.begin() + (long)i);
        return true;
    }
    return false;
}

// Issue #24 fail-on-land (cargo): when the player docks anywhere, drop any
// cargo consignment whose dest_base isn't this dock (cargo jettisoned, no
// reward, no comm payout). Matches the rule that landing without delivering
// fails the contract. Other (non-cargo) mission types aren't auto-failed
// here — they persist until the player delivers or manually abandons, so
// a defend/patrol can still span multiple visits.
void fail_cargo_on_dock(PlayerState& p, const std::string& at_base) {
    for (size_t i = 0; i < p.missions.size(); /* manual */) {
        ActiveMission& am = p.missions[i];
        if (am.type != (int)MissionType::CargoDelivery) { ++i; continue; }
        // Story deliveries own their failure/completion rules in campaign.cpp.
        // Keep the giver check for saves made before MissionSource::Fixer.
        if (am.source == (int)MissionSource::Fixer || am.giver_faction == "Fixer") {
            ++i;
            continue;
        }
        if (am.dest_base == at_base) { ++i; continue; }   // at target — keep
        // Off-target dock: cargo goes (jettisoned), mission fails (no reward).
        const std::string title = am.title;
        player::remove_cargo(p, am.commodity_id, am.units);
        std::printf("[missions] FAIL on dock at '%s': %s\n",
                    at_base.c_str(), title.c_str());
        comm::push("Cargo contract failed: landed at the wrong base.",
                   /*taunt=*/false);
        p.missions.erase(p.missions.begin() + (long)i);
    }
}

// ---- in-flight progress + generic completion (#13 tracker seam) -------------

bool mark_nav_reached(PlayerState& p, const std::string& mission_id,
                      size_t nav_index) {
    for (ActiveMission& am : p.missions) {
        if (am.id != mission_id) continue;
        // Tolerate a mission whose nav_done wasn't sized yet (e.g. one loaded
        // from a save predating this field): re-derive it from nav_targets.
        if (am.nav_done.size() != am.nav_targets.size())
            am.nav_done.assign(am.nav_targets.size(), (uint8_t)0);
        if (nav_index >= am.nav_done.size()) return false;
        am.nav_done[nav_index] = 1;
        std::printf("[missions] NAV reached: %s nav %zu/%zu\n",
                    am.title.c_str(), nav_index + 1, am.nav_done.size());
        return true;
    }
    return false;
}

bool complete_if_objectives_met(PlayerState& p, const std::string& mission_id) {
    for (size_t i = 0; i < p.missions.size(); ++i) {
        ActiveMission& am = p.missions[i];
        if (am.id != mission_id) continue;

        const MissionType t = (MissionType)am.type;
        bool met = false;
        switch (t) {
            case MissionType::Scout:
            case MissionType::Patrol: {
                // Done when EVERY nav is reached. Scout has exactly one; an
                // empty list (shouldn't happen) never auto-completes.
                met = !am.nav_done.empty();
                for (uint8_t d : am.nav_done) if (!d) met = false;
                break;
            }
            case MissionType::Attack:
            case MissionType::DefendBase:
                // Done when the required hostiles are cleared at the target /
                // around the base (progress counter driven by #13/#15).
                met = am.hostiles_required > 0 &&
                      am.progress >= am.hostiles_required;
                break;
            case MissionType::CargoDelivery:
            case MissionType::Bounty:
                // These settle through complete_delivery() / on_target_destroyed();
                // not this generic path.
                return false;
        }
        if (!met) return false;

        char line[160];
        std::snprintf(line, sizeof(line),
                      "%s objective complete. %lld cr transferred.",
                      type_label(t), (long long)am.reward);
        pay_and_drop(p, i, line);
        return true;
    }
    return false;
}

// ---- status / panel seam (Navmap mission status, np-19.3) -----------------
//
// Single source of truth for the per-type mission status text. Both the
// in-flight readout (#18, build_mission_objectives) and the navmap mission
// panel (this issue) call this — keeps their formatting in lockstep.

MissionStatus mission_status(const ActiveMission& am,
                             const StarSystem& sys,
                             const std::string& current_system_id) {
    MissionStatus s;
    const MissionType type = (MissionType)am.type;
    // Cargo's "where do I deliver" lives on dest_system; every other type's
    // action system lives on target_system. That's the field the panel uses
    // to decide whether to append "→ <System>" or not.
    const std::string& tgt_sys_id =
        (type == MissionType::CargoDelivery) ? am.dest_system : am.target_system;
    s.in_current_system = !tgt_sys_id.empty() && (tgt_sys_id == current_system_id);
    s.target_system.clear();
    if (!s.in_current_system && !tgt_sys_id.empty())
        s.target_system = tgt_sys_id;       // raw id; panel display-name lookup is up to it

    char buf[160];
    switch (type) {
    case MissionType::Patrol: {
        int done = 0;
        for (uint8_t d : am.nav_done) done += (d != 0);
        const int total = am.nav_targets.empty() ? am.nav_count
                                                  : (int)am.nav_targets.size();
        std::snprintf(buf, sizeof(buf), "PATROL %d/%d", done, total);
        break;
    }
    case MissionType::Scout: {
        const std::string nav = am.nav_targets.empty() ? std::string("?")
                                                       : am.nav_targets.front();
        std::snprintf(buf, sizeof(buf), "SCOUT: reach %s", nav.c_str());
        break;
    }
    case MissionType::Attack: {
        const int need = am.hostiles_required > 0 ? am.hostiles_required
                                                  : am.count_required;
        std::snprintf(buf, sizeof(buf), "ATTACK %d/%d", am.progress, need);
        break;
    }
    case MissionType::DefendBase: {
        const int need = am.hostiles_required > 0 ? am.hostiles_required
                                                  : am.count_required;
        const bool secure = (need > 0 && am.progress >= need);
        // base_label falls back to base_id when the base isn't in `sys`,
        // which is the right behavior for cross-system rows too.
        std::string nm;
        for (const NavPointDef& n : sys.nav_points)
            if (n.base_id == am.target_base && !n.name.empty()) { nm = n.name; break; }
        if (nm.empty()) nm = am.target_base;
        std::snprintf(buf, sizeof(buf), "DEFEND %s: %s",
                      nm.c_str(), secure ? "secure" : "hostiles");
        break;
    }
    case MissionType::Bounty:
        std::snprintf(buf, sizeof(buf), "BOUNTY %s %d/%d",
                      am.target_faction.c_str(), am.progress, am.count_required);
        break;
    case MissionType::CargoDelivery:
        if (s.in_current_system) {
            // Mirrors #18 verbatim ("READY TO DELIVER") so the panel and the
            // in-flight readout can't drift apart.
            std::snprintf(buf, sizeof(buf), "READY TO DELIVER");
        } else {
            // Cross-system: include the commodity and the destination base
            // id so the panel can identify it; the panel appends the
            // destination SYSTEM as a separate "→ X" line.
            std::snprintf(buf, sizeof(buf), "DELIVER %s -> %s",
                          am.commodity_id.c_str(),
                          am.dest_base.c_str());
        }
        break;
    default:
        std::snprintf(buf, sizeof(buf), "%s", am.title.c_str());
        break;
    }
    s.text = buf;
    return s;
}

// ---- mission kill progress (np-ma2.1 death pass) ----------------------------
// NOTE: this credits mission progress for the destruction of a qualifying
// target REGARDLESS of who landed the kill. That's deliberate — a third
// party stealing your bounty/hunt target must not soft-lock the contract
// (mission forces aren't replaced after combat losses). Reputation + the
// lifetime-kill scoreboard are handled separately and stay player-only.

int on_target_destroyed(PlayerState& p, Faction victim,
                        const std::string& current_system) {
    const char* victim_name = faction::to_name(victim);
    int advanced = 0;

    // A kill only counts toward a bounty hunted in one of its posted systems.
    // An empty region means "any system" (safety fallback for older saves /
    // generators that didn't stamp a region).
    auto in_region = [&](const ActiveMission& am) {
        if (am.bounty_region.empty()) return true;   // "any"
        for (const std::string& sys : am.bounty_region)
            if (sys == current_system) return true;
        return false;
    };

    for (size_t i = 0; i < p.missions.size(); /* manual */) {
        ActiveMission& am = p.missions[i];
        if (am.type != (int)MissionType::Bounty ||
            am.target_faction != victim_name ||
            am.progress >= am.count_required ||
            !in_region(am)) {
            ++i;
            continue;
        }
        ++am.progress;
        ++advanced;
        std::printf("[missions] BOUNTY progress: %s %d/%d\n",
                    am.title.c_str(), am.progress, am.count_required);
        char line[128];
        std::snprintf(line, sizeof(line), "Bounty: %s %d/%d",
                      victim_name, am.progress, am.count_required);
        comm::push(line, /*taunt=*/false);

        if (am.progress >= am.count_required) {
            char done[128];
            std::snprintf(done, sizeof(done),
                          "Bounty complete. %lld cr transferred.",
                          (long long)am.reward);
            pay_and_drop(p, i, done);   // shared payout path
            continue;   // don't advance i — we removed this entry
        }
        ++i;
    }

    // Attack / DefendBase: count the qualifying kill per-kill. The mission
    // force spawns well outside the tracker's 6km nav bubble
    // (encounters.cpp mission_spawn_point), so update_clear()'s at-nav
    // "hostiles seen" gate rarely fires — killing the spawned force is what
    // should advance progress. We do NOT settle here: the next
    // mission_tracker::tick() runs complete_if_objectives_met() (every frame
    // for attack/defend), keeping a single completion path and sidestepping
    // erase-mid-iteration hazards. (The existing update_clear() wholesale-set
    // becomes a harmless fallback: its `progress < hostiles_required` guard no
    // longer fires once per-kill has reached the target.)
    for (ActiveMission& am : p.missions) {
        const MissionType t = (MissionType)am.type;
        if (t != MissionType::Attack && t != MissionType::DefendBase) continue;
        if (am.target_faction != victim_name) continue;
        if (am.target_system != current_system) continue;
        if (am.progress >= am.hostiles_required) continue;

        ++am.progress;
        ++advanced;
        const char* tag = (t == MissionType::Attack) ? "Attack" : "Defend";
        std::printf("[missions] %s progress: %s %d/%d\n",
                    tag, am.title.c_str(), am.progress, am.hostiles_required);
        char line[128];
        std::snprintf(line, sizeof(line), "%s: %d/%d",
                      tag, am.progress, am.hostiles_required);
        comm::push(line, /*taunt=*/false);
    }
    return advanced;
}

// ---- label helpers ---------------------------------------------------------

// Short uppercase tag for the Mission Computer UI and headless test. Never
// nullptr — falls back to "?" for an unknown value.
const char* type_label(MissionType t) {
    switch (t) {
        case MissionType::Patrol:        return "PATROL";
        case MissionType::Scout:         return "SCOUT";
        case MissionType::Attack:        return "ATTACK";
        case MissionType::DefendBase:    return "DEFEND";
        case MissionType::Bounty:        return "BOUNTY";
        case MissionType::CargoDelivery: return "CARGO";
    }
    return "?";
}

// Display name for a mission source — feeds briefing text + any UI that
// calls out where the offer came from. Never nullptr.
const char* source_label(MissionSource s) {
    switch (s) {
        case MissionSource::Computer:         return "Mission Computer";
        case MissionSource::MercenariesGuild: return "Mercenaries Guild";
        case MissionSource::MerchantsGuild:   return "Merchants Guild";
        case MissionSource::Fixer:             return "Fixer";
    }
    return "?";
}

// ---- Mission Computer screen body -------------------------------------------
#ifndef MISSIONS_HEADLESS

namespace {

// HUD palette echoing base_screens.cpp / economy.cpp.
constexpr ImU32 kAmber = IM_COL32(255, 217,  77, 255);
constexpr ImU32 kGreen = IM_COL32(120, 230, 120, 255);
constexpr ImU32 kGrey  = IM_COL32(150, 158, 168, 255);

// ---- column / progress text helpers ----------------------------------------

// Count of nav points already reached on an active visit-a-nav mission.
int navs_done(const ActiveMission& am) {
    int n = 0;
    for (uint8_t b : am.nav_done) if (b) ++n;
    return n;
}

// The type-aware "Destination / Target" cell for an AVAILABLE offer.
std::string board_target_text(const Mission& m) {
    char buf[256];
    switch (m.type) {
        case MissionType::CargoDelivery:
            std::snprintf(buf, sizeof buf, "%s (%s)",
                          m.dest_base_name.c_str(), m.dest_system_name.c_str());
            break;
        case MissionType::Bounty: {
            std::string region;
            for (const std::string& r : m.bounty_region) {
                if (r.empty()) continue;
                if (!region.empty()) region += ", ";
                region += r;
            }
            if (region.empty())
                std::snprintf(buf, sizeof buf, "%d x %s",
                              m.count_required, m.target_faction.c_str());
            else
                std::snprintf(buf, sizeof buf, "%d x %s  [%s]",
                              m.count_required, m.target_faction.c_str(), region.c_str());
            break;
        }
        case MissionType::Scout:
        case MissionType::Attack:
            std::snprintf(buf, sizeof buf, "%s (%s)",
                          m.nav_targets.empty() ? "nav" : m.nav_targets.front().c_str(),
                          m.target_system.c_str());
            break;
        case MissionType::Patrol:
            std::snprintf(buf, sizeof buf, "%d nav points in %s",
                          m.nav_count, m.target_system.c_str());
            break;
        case MissionType::DefendBase:
            std::snprintf(buf, sizeof buf, "%s (%s)",
                          m.target_base.c_str(), m.target_system.c_str());
            break;
        default:
            std::snprintf(buf, sizeof buf, "-");
            break;
    }
    return buf;
}

// The type-aware "Progress" cell for an ACTIVE mission. `good` => render it in
// the green "objective met / ready" colour. Reads only #13/#15 state.
struct ProgressCell { std::string text; bool good = false; };
ProgressCell active_progress(const ActiveMission& am, const std::string& here_base) {
    char buf[160];
    switch ((MissionType)am.type) {
        case MissionType::CargoDelivery:
            if (am.dest_base == here_base) return { "ready to deliver", true };
            std::snprintf(buf, sizeof buf, "-> %s", am.dest_base.c_str());
            return { buf, false };
        case MissionType::Bounty:
            std::snprintf(buf, sizeof buf, "%d / %d kills", am.progress, am.count_required);
            return { buf, am.count_required > 0 && am.progress >= am.count_required };
        case MissionType::Scout: {
            const bool done = !am.nav_done.empty() && am.nav_done[0];
            return { done ? "surveyed" : "pending", done };
        }
        case MissionType::Patrol: {
            const int total = am.nav_targets.empty() ? am.nav_count : (int)am.nav_targets.size();
            const int done  = navs_done(am);
            std::snprintf(buf, sizeof buf, "%d / %d nav points", done, total);
            return { buf, total > 0 && done >= total };
        }
        case MissionType::Attack:
        case MissionType::DefendBase: {
            const int need = am.hostiles_required;
            if (need > 0 && am.progress >= need) return { "area secured", true };
            std::snprintf(buf, sizeof buf, "%d / %d destroyed", am.progress, need);
            return { buf, false };
        }
    }
    return { "-", false };
}

// ---- guild membership gate (#16) -------------------------------------------

bool source_is_guild(MissionSource s) {
    return s == MissionSource::MercenariesGuild || s == MissionSource::MerchantsGuild;
}
bool& guild_flag(PlayerState& p, MissionSource s) {
    return (s == MissionSource::MercenariesGuild) ? p.merc_guild_member
                                                  : p.merchant_guild_member;
}
int64_t guild_join_fee(MissionSource s) {
    return (s == MissionSource::MercenariesGuild) ? player::k_merc_guild_fee
                                                  : player::k_merchant_guild_fee;
}

// Non-member guild body: dues line + a JOIN button that pays via
// player::spend_credits and flips the membership flag. Keeps the board hook
// self-contained (gate lives WITH the board it guards) rather than relying on
// the caller to have gated already.
void draw_join_prompt(BaseContext& ctx, MissionSource source) {
    PlayerState&  p      = *ctx.player;
    bool&         member = guild_flag(p, source);
    const int64_t fee    = guild_join_fee(source);
    const char*   name   = source_label(source);

    ImGui::SetCursorScreenPos(ImVec2(40, 96));
    ImGui::PushStyleColor(ImGuiCol_Text, kAmber);
    ImGui::Text("%s membership costs %lld cr (one-time).", name, (long long)fee);
    ImGui::PopStyleColor();

    ImGui::SetCursorScreenPos(ImVec2(40, 124));
    ImGui::Text("Credits on hand: %lld", (long long)p.credits);

    ImGui::SetCursorScreenPos(ImVec2(40, 160));
    ImGui::BeginDisabled(p.credits < fee);
    if (ImGui::Button("JOIN GUILD", ImVec2(160, 36))) {
        if (player::spend_credits(p, fee)) {
            member = true;
            sfx::ui_click();
            std::printf("[missions] joined %s (-%lld cr, %lld left)\n",
                        name, (long long)fee, (long long)p.credits);
        }
    }
    ImGui::EndDisabled();
}

// ---- the shared board renderer (Mission Computer + both guilds) ------------

void draw_board(BaseContext& ctx, MissionSource source) {
    PlayerState& p = *ctx.player;

    // Guild screens gate on a paid membership (#16): show the dues/JOIN prompt
    // until the player joins, then the board.
    if (source_is_guild(source) && !guild_flag(p, source)) {
        draw_join_prompt(ctx, source);
        return;
    }

    const ShipClass* klass = ship_class::find(p.ship_class_name);
    const int capacity = player::cargo_capacity(p, klass);
    const int used     = player::cargo_units_used(p);

    const float dpi = sapp_dpi_scale();
    const float sw  = (float)sapp_width()  / dpi;
    const float sh  = (float)sapp_height() / dpi;

    // Totals strip.
    ImGui::SetCursorScreenPos(ImVec2(28, 62));
    ImGui::PushStyleColor(ImGuiCol_Text, kAmber);
    ImGui::Text("CREDITS  %lld", (long long)p.credits);
    ImGui::SameLine(260);
    ImGui::Text("CARGO  %d / %d units", used, capacity);
    ImGui::SameLine(520);
    ImGui::Text("ACTIVE  %zu", p.missions.size());
    ImGui::PopStyleColor();

    // Split the screen height between the two panes (Available + Active).
    // The vertical accounting must clear:
    //   * 92  top reservation   — totals strip (62..92) and the "AVAILABLE MISSIONS" label (at y=92).
    //   * 24  inter-pane gap    — gap between the bottom of pane #1 and the "ACTIVE MISSIONS" label at y=92+child_sz.y+24.
    //   * 18  label line        — ~18 px for "ACTIVE MISSIONS" itself.
    //   * 70  bottom reservation — BACK button at ss.h - 56 spanning 32 px, so clear with slack.
    // The old formula (sh - 92 - 70) forgot the 24+18 gap-and-label, so the
    // active child overlapped the BACK button and only its bottom sliver
    // was clickable (issue #1).
    const ImVec2 child_sz(sw - 56, (sh - 92 - 24 - 18 - 70) * 0.5f);


    constexpr ImGuiTableFlags tflags =
        ImGuiTableFlags_RowBg | ImGuiTableFlags_BordersInnerH |
        ImGuiTableFlags_ScrollY | ImGuiTableFlags_SizingFixedFit;

    // ---- available board ----
    ImGui::SetCursorScreenPos(ImVec2(28, 92));
    ImGui::PushStyleColor(ImGuiCol_Text, kAmber);
    ImGui::TextUnformatted("AVAILABLE MISSIONS");
    ImGui::PopStyleColor();

    // The mission board sits over detailed room art. Keep that atmosphere,
    // but give both tables enough smoked-glass opacity for multiline mission
    // text to remain legible instead of fighting every pixel underneath.
    ImGui::PushStyleColor(ImGuiCol_ChildBg,       ImVec4(0.025f, 0.030f, 0.040f, 0.78f));
    ImGui::PushStyleColor(ImGuiCol_TableHeaderBg, ImVec4(0.120f, 0.130f, 0.160f, 0.92f));
    ImGui::PushStyleColor(ImGuiCol_TableRowBg,    ImVec4(0.035f, 0.040f, 0.052f, 0.72f));
    ImGui::PushStyleColor(ImGuiCol_TableRowBgAlt, ImVec4(0.075f, 0.080f, 0.095f, 0.76f));

    if (ImGui::BeginChild("##avail", child_sz, false) &&
        ImGui::BeginTable("avail_tbl", 5, tflags, child_sz)) {
        ImGui::TableSetupScrollFreeze(0, 1);
        ImGui::TableSetupColumn("Mission", ImGuiTableColumnFlags_WidthStretch);
        ImGui::TableSetupColumn("Type");
        ImGui::TableSetupColumn("Destination / Target", ImGuiTableColumnFlags_WidthFixed, 280.0f);
        ImGui::TableSetupColumn("Reward");
        ImGui::TableSetupColumn("", ImGuiTableColumnFlags_WidthFixed, 110.0f);
        ImGui::TableHeadersRow();

        for (const Mission& m : board(source)) {
            ImGui::TableNextRow();
            ImGui::PushID(m.id.c_str());

            ImGui::TableNextColumn(); ImGui::TextUnformatted(m.title.c_str());
            if (ImGui::IsItemHovered() && !m.description.empty())
                ImGui::SetTooltip("%s", m.description.c_str());

            ImGui::TableNextColumn();
            ImGui::PushStyleColor(ImGuiCol_Text, kGrey);
            ImGui::TextUnformatted(type_label(m.type));
            ImGui::PopStyleColor();

            ImGui::TableNextColumn();
            ImGui::TextUnformatted(board_target_text(m).c_str());

            ImGui::TableNextColumn();
            ImGui::PushStyleColor(ImGuiCol_Text, kGreen);
            ImGui::Text("%lld", (long long)m.reward);
            ImGui::PopStyleColor();

            ImGui::TableNextColumn();
            const bool ok = can_accept(p, m, capacity);
            ImGui::BeginDisabled(!ok);
            if (ImGui::SmallButton("Accept")) {
                if (accept(p, m, capacity)) sfx::ui_click();
            }
            ImGui::EndDisabled();
            if (!ok && ImGui::IsItemHovered())
                ImGui::SetTooltip("Not enough cargo space");

            ImGui::PopID();
        }
        ImGui::EndTable();
    }
    ImGui::EndChild();

    // ---- active missions ----
    ImGui::SetCursorScreenPos(ImVec2(28, 92 + child_sz.y + 24));
    ImGui::PushStyleColor(ImGuiCol_Text, kAmber);
    ImGui::TextUnformatted("ACTIVE MISSIONS");
    ImGui::PopStyleColor();

    if (ImGui::BeginChild("##active", child_sz, false) &&
        ImGui::BeginTable("active_tbl", 4, tflags, child_sz)) {
        ImGui::TableSetupScrollFreeze(0, 1);
        ImGui::TableSetupColumn("Mission", ImGuiTableColumnFlags_WidthStretch);
        ImGui::TableSetupColumn("Progress", ImGuiTableColumnFlags_WidthFixed, 200.0f);
        ImGui::TableSetupColumn("Reward");
        ImGui::TableSetupColumn("", ImGuiTableColumnFlags_WidthFixed, 200.0f);
        ImGui::TableHeadersRow();

        // Copy ids to act on after the loop — accept/deliver/abandon mutate
        // p.missions, so we never erase mid-iteration of the draw.
        std::string deliver_id, abandon_id;

        for (const ActiveMission& am : p.missions) {
            ImGui::TableNextRow();
            ImGui::PushID(am.id.c_str());

            ImGui::TableNextColumn(); ImGui::TextUnformatted(am.title.c_str());

            ImGui::TableNextColumn();
            {
                const ProgressCell pc = active_progress(am, ctx.base_id);
                if (pc.good)
                    ImGui::TextColored(ImVec4(0.47f, 0.90f, 0.47f, 1.0f), "%s", pc.text.c_str());
                else
                    ImGui::TextUnformatted(pc.text.c_str());
            }

            ImGui::TableNextColumn();
            ImGui::Text("%lld", (long long)am.reward);

            ImGui::TableNextColumn();
            if (am.type == (int)MissionType::CargoDelivery && am.dest_base == ctx.base_id) {
                // Per-button PushID so each Deliver / Abandon gets a unique
                // generated ID. The row already PushID's on am.id, but
                // without these discriminator PushIDs Deliver and Abandon
                // within the SAME row would collide.
                ImGui::PushID("deliver");
                if (ImGui::SmallButton("Deliver")) deliver_id = am.id;
                ImGui::PopID();
                ImGui::SameLine();
            }
            ImGui::PushID("abandon");
            if (ImGui::SmallButton("Abandon")) abandon_id = am.id;
            ImGui::PopID();

            ImGui::PopID();
        }
        ImGui::EndTable();

        if (!deliver_id.empty()) {
            if (complete_delivery(p, deliver_id, ctx.base_id)) sfx::ui_click();
        }
        if (!abandon_id.empty()) {
            if (abandon(p, abandon_id)) sfx::ui_click();
        }
    }
    ImGui::EndChild();
    ImGui::PopStyleColor(4);
}

} // namespace

void register_screen() {
  base_screens::register_screen(BaseScreen::MissionComputer,
      [](BaseContext& c) { draw_board(c, MissionSource::Computer); });
  base_screens::register_screen(BaseScreen::MercenariesGuild,
      [](BaseContext& c) { draw_board(c, MissionSource::MercenariesGuild); });
  base_screens::register_screen(BaseScreen::MerchantsGuild,
      [](BaseContext& c) { draw_board(c, MissionSource::MerchantsGuild); });
}

#else  // MISSIONS_HEADLESS
void register_screen() {}   // no-op in the offline harness
#endif

} // namespace missions
