// AUTOGENERATED by tools/gen_mission_templates.py — do NOT hand-edit.
// Regenerate by running the script (CMake custom_command).
#pragma once
#include <cstddef>
#include <string_view>

namespace missions::templates {

// Source pools.
    // 7 entries.
    inline constexpr std::string_view k_enmy[] = {
        R"gen(merchant)gen",
        R"gen(mercenary)gen",
        R"gen(pirate)gen",
        R"gen(Kilrathi)gen",
        R"gen(militia)gen",
        R"gen(Confederation)gen",
        R"gen(Retro)gen"
    };

    // 110 entries.
    inline constexpr std::string_view k_corp[] = {
        R"gen(The Merchants' Guild)gen",
        R"gen(The Militia)gen",
        R"gen(The Confederation)gen",
        R"gen(Anonymous Employer)gen",
        R"gen(Lynch Enterprises)gen",
        R"gen(Lynch Shipping)gen",
        R"gen(Lynch Mining)gen",
        R"gen(Lynch Security)gen",
        R"gen(The Exploratory Service)gen",
        R"gen(Private Citizen)gen",
        R"gen(Omni, Inc.)gen",
        R"gen(Cerberus Shipping)gen",
        R"gen(Blankenstaff Ltd.)gen",
        R"gen(Tsunami/Azuma, Inc.)gen",
        R"gen(Trebor Corp.)gen",
        R"gen(Tactical Micro Devices)gen",
        R"gen(Izanami Corp.)gen",
        R"gen(Omniscan, Inc.)gen",
        R"gen(Galaxy Resources, Inc.)gen",
        R"gen(Tetsuo Distribution, Ltd.)gen",
        R"gen(Cerebus Shipping)gen",
        R"gen(Tsumami)gen",
        R"gen(Azuma Weapons)gen",
        R"gen(Gemini Export)gen",
        R"gen(The Cardann Group)gen",
        R"gen(Beto's Foodcorp Unltd.)gen",
        R"gen(Tanya/Sepree, Inc.)gen",
        R"gen(Frontier Enterprises)gen",
        R"gen(United Distribution)gen",
        R"gen(TransComm)gen",
        R"gen(Confederated Mining)gen",
        R"gen(MegaCrunch Credit)gen",
        R"gen(Austin Entertainment Group)gen",
        R"gen(Russo Disposal Systems)gen",
        R"gen(Manners Arms and Shielding)gen",
        R"gen(Johnson and Cafrelli, Ltd.)gen",
        R"gen(Apex)gen",
        R"gen(Terraform Corp.)gen",
        R"gen(Hydroshock Manufacturing)gen",
        R"gen(Universal Imports)gen",
        R"gen(Transector Plus)gen",
        R"gen(Fellowship Systems)gen",
        R"gen(Skybird Scanners)gen",
        R"gen(Rolling Hills, Unltd.)gen",
        R"gen(Valle Brothers)gen",
        R"gen(Frake Packaging)gen",
        R"gen(Capri Mining)gen",
        R"gen(Nexus Mining)gen",
        R"gen(Taurus Mining)gen",
        R"gen(Saturn Mining)gen",
        R"gen(Deep Space Asteroid Mining)gen",
        R"gen(Dell Refineries)gen",
        R"gen(Nicholson Refineries)gen",
        R"gen(Hendershot Mining)gen",
        R"gen(Starfield Cruises)gen",
        R"gen(Maximum Pleasure)gen",
        R"gen(Ultima Resorts)gen",
        R"gen(Infrared Detection Systems)gen",
        R"gen(Total Eclipse)gen",
        R"gen(Merry Rover)gen",
        R"gen(Mycroft Mining)gen",
        R"gen(Middleton Securities)gen",
        R"gen(First Bank of Gemini)gen",
        R"gen(Gemini Savings and Loan)gen",
        R"gen(Jefferson Confederal)gen",
        R"gen(AllSafe Retrograde)gen",
        R"gen(Bridesmaid Enterprises)gen",
        R"gen(TDR Symposium)gen",
        R"gen(Borderline, Inc.)gen",
        R"gen(Averson Dynamics)gen",
        R"gen(Citation)gen",
        R"gen(Hawkeye Security)gen",
        R"gen(Renegade Weapon Systems)gen",
        R"gen(TipTop Systems)gen",
        R"gen(AntiStealth, Ltd.)gen",
        R"gen(MicroDeath Delivery)gen",
        R"gen(AutoNav)gen",
        R"gen(Second Star)gen",
        R"gen(QuarterMast Nav and Chart)gen",
        R"gen(Parsec Mining)gen",
        R"gen(First Strike, Inc.)gen",
        R"gen(Heistand Forecasting)gen",
        R"gen(Abyss Minerals)gen",
        R"gen(EnvironMental, Unltd.)gen",
        R"gen(Tarsus)gen",
        R"gen(MetroScan)gen",
        R"gen(The McLaughlin Company)gen",
        R"gen(Delta Resorts)gen",
        R"gen(Gamma-Way)gen",
        R"gen(Thermal Optics)gen",
        R"gen(Scorpio Consulting)gen",
        R"gen(Obsession, Inc.)gen",
        R"gen(The Outskirt Consortium )gen",
        R"gen(Big Bang Pharmaceuticals)gen",
        R"gen(Cannon Research Group)gen",
        R"gen(Capital Investments)gen",
        R"gen(Universal Charter)gen",
        R"gen(Martin Swig Distillery)gen",
        R"gen(FiberLink)gen",
        R"gen(Origin Systems, Inc.)gen",
        R"gen(Electronic Arts, Inc.)gen",
        R"gen(Lehman Carbonshares)gen",
        R"gen(Black Hole Retrievals)gen",
        R"gen(Triple Play Enterprises)gen",
        R"gen(Oxford Research Foundation)gen",
        R"gen(Castro Memorial Foundation)gen",
        R"gen(Grim Reaper Systems)gen",
        R"gen(Voight, Inc.)gen",
        R"gen(CyberSoft)gen",
        R"gen(Brainwave Instruments)gen"
    };


// Per-type tables (PTRL/SCOU/DFND/CRGO/ATAK/BNTY). One-line summary
// + N copy variants per type. Token substitution is left to the
// caller: src/missions.cpp's render_briefing() walks the chosen
// copy template and substitutes every supported $XX token.
// ---- PTRL ----
inline constexpr std::string_view k_ptrl_summary = R"gen(
Patrol $NN nav points in the $DS system, $EN encounters likely.

Nav points are programmed in your ship's nav computer.

$CL pays $PY credits.)gen";
inline constexpr std::size_t    k_ptrl_count   = 10;
    // 10 entries.
    inline constexpr std::string_view k_ptrl_copy[] = {
        R"gen($DB seeks patrol of $NN designated nav points in the $DS system. Encounter with $EN ships possible. Completed tour pays $PY credits.)gen",
        R"gen($CL wants you to patrol $NN nav points in the $DS system and strike any $EN ships encountered. This run pays $PY credits upon completion.)gen",
        R"gen($DB base concerned about $EN infiltration solicits patrol of $NN nav points in the $DS system. Employer will pay $PY credits to any pilot who will engage $EN vessels.)gen",
        R"gen($DB base needs mercenary to patrol $NN designated nav points in the $DS system, willing to pay $PY credits for service. Clandestine $EN activity reported in the vicinity.)gen",
        R"gen(Capable pilot required to patrol $NN nav points in the $DS system. $CL pays $PY credits to eliminate $EN presence after mission's end.)gen",
        R"gen($CL seeks patrol in the $DS system along $NN nav points. Insurgent activity from $EN forces likely. Offering $PY credits upon conclusion of mission.)gen",
        R"gen(SERVE! $DB base seeks adventurous pilot to patrol up to $NN nav points in the $DS system for $EN build-up. Pending successful patrol, $PY credits will be deposited into your account.)gen",
        R"gen(PUBLIC NOTICE. Patrol duty available in $DS system. Intermittent $EN encroachment threatens local bases. $PY credits paid upon successful patrol of $NN designated nav points.)gen",
        R"gen(Trouble in $DS system with $EN forays requires $DB base to solicit help. $CL offers $PY credits to pilot who will patrol $NN nav points. Payment will be electronically transferred to your account.)gen",
        R"gen(Opportunity exists for pilot to patrol $NN nav points in the $DS system, targeting $EN trespassers, at a payment of $PY credits.  $CL guarantees payment following completion of mission.)gen"
    };

// ---- SCOU ----
inline constexpr std::string_view k_scou_summary = R"gen(
Scout Nav $DN, $DS system for $EN presence.

$CL pays $PY credits.)gen";
inline constexpr std::size_t    k_scou_count   = 10;
    // 10 entries.
    inline constexpr std::string_view k_scou_copy[] = {
        R"gen(Pilot needed to reconnoiter $EN presence at Nav $DN in the $DS system. Run pays $PY credits. Compensation credited to your account after mission completion.)gen",
        R"gen(Looking for pilot to scout region of Nav $DN in the $DS system to ensure space lanes remain open for safe travel. Successful excursion brings automatic disbursement of $PY credits.)gen",
        R"gen(Able pilot with scouting experience needed to survey Nav $DN in the $DS system. Possibility of $EN encounter exists. Destruction of $EN forces will result in payment of $PY credits.)gen",
        R"gen($CL seeking freelancer to scout perimeter of Nav $DN in $DS system for hostiles of undetermined type. Employer will pay $PY credits to anyone who can end enemy harrassment of shipping lanes.)gen",
        R"gen($CL seeks discreet pilot to scout Nav $DN in the $DS system with intent to eliminate any hostiles encountered. Payment of $PY credits will follow successful engagement.)gen",
        R"gen(Easy money. $CL seeks scout to assess $EN presence in the $DS system, Nav $DN. Automatic reporting, automatic deposit of $PY credits.)gen",
        R"gen(Attention! $CL needs scout for recon of possible $EN activity on Nav $DN in the $DS system. Compensation of $PY credits to be electronically transferred.)gen",
        R"gen(Militia seeks scout to investigate disappearance of military craft at Nav $DN in the $DS system. Compensation set at $PY credits.)gen",
        R"gen($CL highly desirous of scout willing to assess and eliminate $EN forces at Nav $DN in $DS system. Payment of $PY credits electronically deposited following successful mission.)gen",
        R"gen(High pay, high risk. Pilot needed to scout Nav $DN in $DS system to determine strength of $EN forces concentrated there. Will receive $PY credits in payment at mission's end.)gen"
    };

// ---- DFND ----
inline constexpr std::string_view k_dfnd_summary = R"gen(
Defend base $DB in the $DS system from a $EN attack.

Base $DB pays $PY credits.)gen";
inline constexpr std::size_t    k_dfnd_count   = 10;
    // 10 entries.
    inline constexpr std::string_view k_dfnd_copy[] = {
        R"gen(Attack against $DB at Nav $DN in $DS system prompts recruitment of armed assistance. $PY credits transferred to account of pilot able to repel $EN hostilities.)gen",
        R"gen(As a precaution against $EN incursions into $DB's space, capable combat veteran wanted. Report to base in the $DS system for automatic payment of $PY credits following lessened tensions in the system.)gen",
        R"gen($DS system experiencing trouble with $EN trespassers. To quell tourist unrest, $DB seeks tough pilot. $PY credits will be automatically credited with deterrence of offending vessels.)gen",
        R"gen(Due to overwhelming opposition, $DB in $DS system seeks reinforcements. Qualified pilots unafraid of strong $EN blockade are offered $PY credits pending successful defense of base.)gen",
        R"gen(Base under siege. Fighter pilots needed to combat $EN aggression at $DB in the $DS system. When calm returns, $PY credits reward will be automatically credited to your account.)gen",
        R"gen(Hazard pay. Militia endeavors to employ warrior pilots for battle at $DB in the $DS system. Completed tour pays $PY credits.)gen",
        R"gen($DB in $DS system urgently wishes to supplement defense forces. Strike seems likely due to increased $EN activity along surrounding nav points. $PY credits paid after assault repelled.)gen",
        R"gen($CL in $DS system offers $PY credits for master pilot to defend $DB against $EN attacks. Payment automatically available following realization of objective.)gen",
        R"gen(Commandos sought for surgical defense of $DB in the $DS system. Mission has an anticipated short duration and a price tag of $PY credits at mission's end.)gen",
        R"gen(Reinforcements needed in the $DS system immediately. Experienced fighters are urged to report to $DB prepared for combat. Instant compensation of $PY credits made upon eradication of $EN threat.)gen"
    };

// ---- CRGO ----
inline constexpr std::string_view k_crgo_summary = R"gen(
Deliver cargo of $CG to $DB in the $DS system.

$CL pays $PY credits.)gen";
inline constexpr std::size_t    k_crgo_count   = 15;
    // 15 entries.
    inline constexpr std::string_view k_crgo_copy[] = {
        R"gen($CL seeks $CG delivery. Time is of the essence.  Payment of $PY credits is contingent upon unscathed delivery of cargo to $DB base in the $DS system.)gen",
        R"gen(Capitalize on this opportunity! Pick up a load of $CG and deliver to $DB base in $DS system. A $EN encounter is possible. $CL pays $PY credits per shipment.)gen",
        R"gen(Fast cash. $CL seeks pilot to ship load of $CG to client on base $DB in the $DS system. Track record of reliability with the Merchants' Guild a plus. Paying $PY credits for successful delivery.)gen",
        R"gen(Rush order. High demand for $CG on base $DB in system $DS necessitates employment of qualified privateer immediately. Automatic deposit of $PY credits at mission's end hinges on successful delivery.)gen",
        R"gen(Temporary opening for pilot familiar with the $DS system. $CL wants a load of $CG transported to $DB base, $EN encounters are possible. $PY credits available for the right pilot.)gen",
        R"gen($CG requires delivery to base $DB in the $DS system. Delivery of goods prompts autocredit of $PY credits.)gen",
        R"gen(Talented pilot needed to ship $CG from here to base $DB in the $DS system. $PY credits guaranteed for safe delivery.)gen",
        R"gen(Fly for cash. Pick up load of $CG and ship to the $DS system, base $DB. Paying $PY credits on delivery.)gen",
        R"gen(Short fuse! Pilot needed to ship $CG to $DB base in the $DS system. $CL is paying $PY credits for intact delivery.)gen",
        R"gen(Shipment of $CG awaits proficient pilot for delivery to $DB base, $DS system nets the pilot $PY credits.)gen",
        R"gen(Cargo must get through!  Offering $PY credits for delivery of $CG to the $DB base in the $DS system. Payment posted after delivery is secured.)gen",
        R"gen(Trouble with $EN ambushes along shipping lanes between here and $DS system requires employment of pilot with combat experience to transfer $CG to $DB base. $PY credits follows completion of mission.)gen",
        R"gen(Dangerous run! Certain $EN attack of any pilot entering $DS system, but load of $CG must be transferred to $DB base. Any pilot able to complete delivery will earn autocredit of $PY credits.)gen",
        R"gen($CL seeks mercenary to deliver $CG to $DB base in $DS system. Pick up cargo and complete delivery for payment of $PY credits.)gen",
        R"gen(Merc sought to transfer cargo of $CG between here and $DB base, in $DS system. Compensation of $PY credits guaranteed with completion of transfer.)gen"
    };

// ---- ATAK ----
inline constexpr std::string_view k_atak_summary = R"gen(
Attack $EN ships currently at Nav $DN in the $DS system.

$CL pays $PY credits.)gen";
inline constexpr std::size_t    k_atak_count   = 10;
    // 10 entries.
    inline constexpr std::string_view k_atak_copy[] = {
        R"gen(Big bucks for dedicated professional. Need $EN presense eliminated at Nav $DN in the $DS system. Paying $PY credits for thorough work.)gen",
        R"gen(High risk contract. $CL in system $DS seeks proficient pilots for flight restriction enforcement against $EN ships at Nav $DN. Pay of $PY credits commensurate with number of enemy hits.)gen",
        R"gen(Grave insult against honor of Azuma Weapons demands retribution. $PY credits automatic upon execution of $EN at Nav $DN in the $DS system. No prisoners, please.)gen",
        R"gen(Combat veteran required to eliminate $EN from Nav $DN in the $DS system. Dispatch of targeted enemy is good for $PY credits deposited automatically to your account.)gen",
        R"gen(Hard, ruthless freelancer sought to clear traffic lane in $DS system at Nav $DN of $EN presense. $CL guarantees $PY credits immediately pending conclusion of mission.)gen",
        R"gen(Ace pilots needed to clear shipping lanes of $EN assaults. Proceed to Nav $DN in the $DS system. Reward of $PY credits for termination of engagement.)gen",
        R"gen(Merc needed to help make business flights safe. Search and destroy $EN ships at Nav $DN in the $DS system. $PY credits for hit will be automatically credited to account.)gen",
        R"gen(Deadly patrol. Experienced mercenary needed to sweep through Nav $DN in the $DS system. Ships of $EN origin frequent this area. Elimination of $EN brings immediate payment of $PY credits.)gen",
        R"gen(Aggravating $EN trouble in $DS system. Pilot with knowledge of $EN combat techniques should hit Nav point $DN, track down and kill acquired targets. $PY credits paid for successful run.)gen",
        R"gen(Disrupt $EN convoys moving through $DS system at Nav $DN and earn $PY credits. Pilot bringing engagement of targets to successful conclusion receives instant automatic payment.)gen"
    };

// ---- BNTY ----
inline constexpr std::string_view k_bnty_summary = R"gen(
Bounty offered for the eradication of a rogue $EN, somewhere in the $DO systems.

$CL will pay $PY credits.)gen";
inline constexpr std::size_t    k_bnty_count   = 15;
    // 15 entries.
    inline constexpr std::string_view k_bnty_copy[] = {
        R"gen($CL offers reward for killing a rogue $EN, best sought between $DS systems. $PY credits tendered by automatic transfer.)gen",
        R"gen($CL has posted a bounty for the elimination of a $EN, most probably found in the $DO systems. Last reported in the vicinity of $D1. Payment of $PY credits is automatic and immediate.)gen",
        R"gen($CL offers blood money to any mercenary who can rid the $DS systems of a $EN vessel. Begin search in system $D1. Success nets you $PY credits in compensation.)gen",
        R"gen(Help keep vital shipping lanes open. A bounty of $PY credits will be electronically transferred to any pilot who can eradicate a $EN ship in the $DO systems.)gen",
        R"gen(Deadly $EN operating out of $DO systems is disrupting free trade. $CL will auto-post reward of $PY credits to your account for destruction of $EN vessel.)gen",
        R"gen(Dead or alive! $CL wants $EN. Last seen in the vicinity of $DO systems. Bounty of $PY credits paid following termination of target.)gen",
        R"gen(Urgent! Stray $EN ship somewhere near the $DO systems. Find it and destroy it. $CL will monitor the mission closely. Upon destruction of the ship, your account will be credited $PY credits.)gen",
        R"gen(Reward of $PY credits is hereby posted for the death of a $EN, last spotted in $D1 system. May be traveling to $D2.)gen",
        R"gen(Bounty hunter needed immediately for termination of a $EN in the $D1 system. Subject may have fled to the $D2. $PY credits automatically deposited after successful operation.)gen",
        R"gen(Murderous $EN marauding through $DS systems, last sighted in the $D1 system. $PY credits offered to any combat ready pilot who can stop the madness.)gen",
        R"gen(Enemy $EN is obliterating $CL ships in the $DS systems. Last spotted near the $D1 system.  Guaranteed auto-deposit of $PY credits for anyone who can track and destroy intruding vessel.)gen",
        R"gen(Anonymous privateer is subcontracting work to qualified pilot on behalf of $CL. Assignment involves a bounty of $PY credits posted for a $EN ship, last seen near $DS systems.)gen",
        R"gen(Can you stop $EN sniper attacks? If the answer is 'yes', search systems $DS and hit your target for a reward of $PY credits.)gen",
        R"gen(Are you up to the challenge? He's murderous, he's a $EN and he's out somewhere in the $DO systems. Receive $PY credits following sanction.)gen",
        R"gen(Slaughter of innocents in $D1 system by a $EN demands retribution. $CL guarantees $PY credits to any freelancer who can track and eliminate threat, possibly fleeing to the $D2.)gen"
    };


} // namespace missions::templates
